### ISSUE TITLE
Error al inicializar el nodo constellation

### ISSUE THREAD

**Issue by alvarogarmig** [alastria/alastria-node#10]
Cuando voy a inicializar el nodo Constellation me dice esto:

`Lock key pair node with password [none]: `

¿Que hay que hacer?

Gracias!

**Comment by marcossanlab** [comment]
Buenos días,

Si dejas la consola sin tocar el teclado, se rellena sola la contraseña.

Un saludo

**Comment by alvarogarmig** [comment]
Quiero decir que al intentar introducir una contraseña me suelta un error de argumento no válido, lo he dejado en blanco que entiendo que por defecto es el valor de [none]
