### ISSUE TITLE
Error durante la ejecución del script bootstrap.sh

### ISSUE THREAD

**Issue by jotorren** [alastria/alastria-node#111]
El script "bootstrap.sh" obliga a que el directorio destino de la instalación esté ubicado bajo el $HOME del usuario que la ejecuta, generando error en caso contrario. Por ejemplo, no es posible instalar el nodo en "/opt".

**Comment by marcossanlab** [comment]
Como una primera aproximación, se cambia la instalación del nodo al script init.sh.

Procederemos a verificar si los cambios son efectivos en una nueva instalación y publicaremos los cambios.

Gracias por el aviso!

**Comment by brunneis** [comment]
Por si sirve de algo, para una instalación personalizada yo ejecuto lo siguiente en el directorio `scripts` (`/opt/alastria`):
```
sed -i 's@~/alastria-node@/opt/alastria@g' init.sh && ./bootstrap.sh
```
@jotorren

**Comment by kikoncuo** [comment]
Implementaciones que resuelven este problema:
1 Usar un path relativo (asume que start.sh se ejecuta siempre desde el mismo sitio)
2 Añadir el path en el que esta instalado a $HOME, y usarlo de esa manera en el script

De todas maneras, urge documentar esto de manera más prominente, hemos tenido el mismo problema un compañero y yo.

**Comment by marcosio** [comment]
Lo tendremos en cuenta para futuras implementaciones.
