### ISSUE TITLE
Error durante el 'build' del monitor

### ISSUE THREAD

**Issue by jotorren** [alastria/alastria-node#112]
La ejecución de '**monitor.sh build**' en un "CentOS Linux release 7.4.1708 (Core)" da el siguiente error:

```
can't load package: package github.com/alastria/monitor: no buildable Go source files in /root/alastria/workspace/src/github.com/alastria/monitor
```

Como workaround, editar el fichero '**scripts/monitor.sh**' y comentar la línea:
`mkdir -p "$GOPATH"/src/github.com/alastria/monitor`

Una vez aplicado este cambio el monitor se descarga y construye correctamente.

**Comment by marcossanlab** [comment]
Corregido, realice de nuevo el proceso de instalación.
