### ISSUE TITLE
Validador: Cannot start mining without etherbase 

### ISSUE THREAD

**Issue by jotorren** [alastria/alastria-node#113]
En el caso de una instalación limpia desde 0, si tras inicializar un nodo validador con "**./init.sh 192.168.99.52 validator myval01**" (_instalación interna para test_), se procede a arrancarlo mediante "**./start.sh clean**", el nodo no se levanta y reporta el error:

```
ERROR[02-21|15:40:13] Cannot start mining without etherbase    err="etherbase address must be explicitly specified"
Fatal: Failed to start mining: etherbase missing: etherbase address must be explicitly specified
```
Dado que el "**init.sh**" no crea ninguna cuenta, basta con hacerlo manualmente utilizando "**geth account new**", por ejemplo en mi caso:

```
[alastriaval01@alastria scripts]$ geth --datadir /home/alastriaval01/alastria/data account new
WARN [02-21|15:47:03] No etherbase set and no accounts found as default
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase:
Repeat passphrase:
Address: {7ce4e63921c8e59ed458de1f0800ad3bf168c8da}
```
Tras ello el validador arranca sin problemas y se sincroniza con el resto de nodos

**Comment by marcossanlab** [comment]
Buenas noches jotorrent,

Ningun validador excepto el nodo Alastria necesitan account en su nodo ya que Istanbul utiliza como coinbase la clave pública del nodo quorum y además no se van a ejecutar smart contracts en estos nodos.

Ruego que te pongas en contacto con nosotros a través de https://alastria.slack.com para que te ayudemos con la puesta en marcha del nodo.

Un cordial saludo!
