### ISSUE TITLE
Versión de Go en CentOS

### ISSUE THREAD

**Issue by jordipainan** [alastria/alastria-node#129]
'bootstrap.sh' instala la versión de Go 1.7.3
Devuelve el siguiente error en CentOS:

![image001](https://user-images.githubusercontent.com/17238033/37085018-56efac76-21f4-11e8-8f19-23ac77a6b5d2.png)

**Comment by marcossanlab** [comment]
Procedemos a subir a golang 1.8.7 en el bootstrap de los nodos.
