### ISSUE TITLE
Después de la ejecución del script bootstrap.sh las variables de entorno no están disponibles

### ISSUE THREAD

**Issue by robinparadise** [alastria/alastria-node#136]
Las variables de entorno:
export GOROOT=/usr/local/go
export GOPATH=$HOME/alastria/workspace
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

no están disponibles, hay que realizar manualmente: source ~/.bashrc

**Comment by robinparadise** [comment]
También después de la ejecución del script bootstrap.sh, el directorio ~/alastria/data no tiene permisos, ya que el directorio pertenece a root.
: para solucionarlo, hay que ejecutar manualmente el comando **sudo chown**
 
dejo las trazas:
```
ubuntu@ip-172-31-47-81:~/alastria-node/scripts$ ./init.sh auto validator node_validator_3
Autodiscovering public host IP ...
Public host IP found: 18.197.82.101
[*] Cleaning up temporary data directories.
mkdir: cannot create directory '/home/ubuntu/alastria/data': Permission denied
mkdir: cannot create directory '/home/ubuntu/alastria/data': Permission denied
mkdir: cannot create directory '/home/ubuntu/alastria/data': Permission denied
ubuntu@ip-172-31-47-81:~/alastria-node/scripts$ **sudo chown ubuntu:ubuntu /home/ubuntu/alastria -R**

```

**Comment by arochaga** [comment]
Hola @robinparadise, en principio hemos resuelto el problema de las variables de entorno en el último commit, gracias por sacarlo a la luz :)

Por otra parte, el problema de los permisos debería resolverse si ejecutas el bootstrap como `sudo -H ./bootstrap.sh`. Confirmanos si así se resuelve y cerramos el issue. Gracias.

Cualquier otro tema nos comentas.

**Comment by robinparadise** [comment]
Ok, todo correcto. Gracias.

**Comment by rbarriuso** [comment]
Veo el mismo problema (o similar) al generar la imagen de Docker:
```
./init.sh: line 136: GOPATH: unbound variable
The command '/bin/sh -c ./init.sh dockerfile $nodetype $nodename' returned a non-zero code: 1
```
