### ISSUE TITLE
Installation of leveldb fails

### ISSUE THREAD

**Issue by michaelkunzmann-sap** [alastria/alastria-node#141]
Hi,

We are trying to install the alastria-node on a Ubuntu 16.04 64bit machine with 2 cpu cores, 4gb of ram and 30gb of disk space.

We followed the instructions in the readme, executing the ```bootstrap.sh``` script. However, it looks like the leveldb installation fails:

```
...
Cloning into 'leveldb'...
remote: Counting objects: 1846, done.
remote: Total 1846 (delta 0), reused 0 (delta 0), pack-reused 1846
Receiving objects: 100% (1846/1846), 997.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1274/1274), done.
Checking connectivity... done.
mkdir out-shared
mkdir out-shared/db
mkdir out-shared/port
mkdir out-shared/table
mkdir out-shared/util
mkdir -p out-shared/helpers/memenv
g++ -I. -I./include -std=c++0x -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX=1 -DLEVELDB_ATOMIC_PRESENT -DHAVE_CRC32C=0 -DHAVE_SNAPPY=0 -O2 -DNDEBUG -DLEVELDB_SHARED_LIBRARY -DLEVELDB_COMPILE_LIBRARY -fPIC -fvisibility=hidden -c db/builder.cc -o out-shared/db/builder.o
In file included from ./port/port.h:14:0,
                 from ./db/filename.h:14,
                 from db/builder.cc:7:
./port/port_posix.h:50:36: error: ‘LEVELDB_IS_BIG_ENDIAN’ was not declared in this scope
 static const bool kLittleEndian = !LEVELDB_IS_BIG_ENDIAN;
                                    ^
Makefile:425: recipe for target 'out-shared/db/builder.o' failed
make: *** [out-shared/db/builder.o] Error 1
```

**Comment by esanchma** [comment]
https://github.com/google/leveldb is failing to compile in Ubuntu LTS with build-essentials (g++ 5.4.0) installed. LevelDB is a dependency for https://github.com/jpmorganchase/quorum . We are going to submit this bug upstream to leveldb and modify the bootstrap script to checkout some good revision instead of the HEAD of their repo in the meantime.

**Comment by esanchma** [comment]
As stated in https://github.com/google/leveldb/issues/569 , LevelDB has migrated from GNU Make to CMake (a version so new its not on the distro repositories), so we are going to install cmake from upstream and then, the new release of leveldb
