### ISSUE TITLE
Timeout error in RPC connection to regular node

### ISSUE THREAD

**Issue by arochaga** [alastria/alastria-node#189]
I am using Python's web3 library to perform RPC operations over a regular node. Usually the operations are received and performed by the node immediately. However, in some cases I am receiving a `Read time out` error out of blue, such as:
```
HTTPConnectionPool(host='13.81.61.232', port=22000): Read timed out. (read timeout=60) (<class 'requests.exceptions.ReadTimeout'>)
```
This is the Web3 connection I am using to the regular node:
```
self.web3 = Web3(RPCProvider(host=self.eth_info.host, port=self.eth_info.port, timeout=60))
```
Is someone facing this same problem, or is it just me? I don't know if the reason for this error is the Web3 library or the RPC port.

**Comment by kikoncuo** [comment]
The timeout is 60ms, that's usually way to short even for a query to block.number, have you tried increasing it?

**Comment by esanchma** [comment]
[web3py docs](https://web3py.readthedocs.io/en/stable/providers.html) states that it supports `IPCProvider`, `HTTPProvider` and `WebsocketProvider`, but not `RPCProvider` .

Anyway, this doesn't seem to be an Alastria bug, so I'm closing it for now
