### ISSUE TITLE
monitor script tries to kill mdadm

### ISSUE THREAD

**Issue by esanchma** [alastria/alastria-node#209]
`./monitor stop`, in an Ubuntu machine, tries to kill the running mdadm daemon, which has cwd `/sbin/mdadm --monitor --pid-file /run/mdadm/monitor.pid --daemonise --scan --syslog`.

mdadm is running as root, so a regular user can't kill it with signals, but some users run Alastria scripts as root.

**Comment by marcosio** [comment]
As it was executed in root context (the service will be started again automaticalli) as if it is executed y user context, the effect is null.

We will change the `monitor.sh stop` for redirect the result of  pkill to `/dev/null`.
