### ISSUE TITLE
Some error checking should be performed when erasing files and directories

### ISSUE THREAD

**Issue by jesus-alastria** [alastria/alastria-node#215]
https://github.com/alastria/alastria-node/blob/6217d0a1bb5727c26a49b945dbede6b9c308c67e/scripts/start.sh#L35-L50
At least some error checking should be performed in order to detect some errors like file and directory permission access (eg. directory was created under different user).
Otherwise, the script is difficult to use from other programs (which may run under different users)

**Comment by marcosio** [comment]
It does not apply.
