### ISSUE TITLE
DIRECTORY_REGULAR.md 

### ISSUE THREAD

**Issue by alastriaxga** [alastria/alastria-node#246]
You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork alastriaxga/alastria-node, so you can send a pull request.

**Comment by marcosio** [comment]
Please, review this [F.A.Q](https://github.com/alastria/alastria-node/wiki/FAQ_EN#howto-pull-request-to-alastria-node).
