### ISSUE TITLE
Calling external contracts from a contract is broken

### ISSUE THREAD

**Issue by blockchain-ctic** [alastria/alastria-node#247]
See this snippet:

```
contract A {
    uint32 constant magic = 12345;

    function getMagic() public view returns (uint32) {
    	return magic;
    }
}

contract B {
  A public remote;

  constructor(A _a) public {
	remote = _a;
  }

  function getRemoteMagic() public view returns (uint32) {
	return remote.getMagic();
  }
}
```
A call to B.getRemoteMagic() should return 12345 but returns 0 instead. This behavior seems to be related to [Quorum Issue #391](https://github.com/jpmorganchase/quorum/issues/391).

I'm attaching a Truffle project featuring the sample code above and a basic test. Note the test works fine on development networks (Ganache) but fails on Alastria.

```
$ truffle test
Compiling ./contracts/A.sol...
Compiling ./contracts/B.sol...
Compiling ./contracts/Migrations.sol...

  Contract: B
    ✓ Testing getMagic

  1 passing (27ms)


$ truffle test --network alastria
Compiling ./contracts/A.sol...
Compiling ./contracts/B.sol...
Compiling ./contracts/Migrations.sol...

  Contract: B
    1) Testing getMagic
    > No events were emitted

  0 passing (18ms)
  1 failing

  1) Contract: B
       Testing getMagic:
     AssertionError: getMagic failed: expected { Object (s, e, ...) } to equal 12345
      at test/magic.js:8:14
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

```
[alastria-example.tar.gz](https://github.com/alastria/alastria-node/files/2192582/alastria-example.tar.gz)

**Comment by kikoncuo** [comment]
This is a common error, it sounds like you are compiling for byzantium, but running on homestead.
solc has a --evm-version option.

Also which version of pragma are you using? trying a really old one should also work (such as version v0.4.8)

Link fo more info https://github.com/ethereum/solidity/issues/4259
