### ISSUE TITLE
initial import

### ISSUE THREAD

**Issue by esanchma** [alastria/alastria-node#251]
We could use git lfs to upload an export of the blockchain (at this point, a 6GB file, compressed to a 2.3 bzip2 file) and do an import in the init script. Then, new nodes would syncronize fast, instead of waiting for ages to synchronize the full blockchain.

**Comment by AlastriaSertec** [comment]
Has anyone calculated how long that node synchronization takes, compared to how much would it save to update it by git?
What should also be, is a method to facilitate the inclusion of new nodes to the network, instead of updating a file in git that others have to read.

**Comment by esanchma** [comment]
>  Has anyone calculated how long that node synchronization takes, compared to how much would it save to update it by git?

At this point, the full sync takes around 6 hours. With import, it would take minutes

> What should also be, is a method to facilitate the inclusion of new nodes to the network, instead of updating a file in git that others have to read.

That is something already available in [Parity](https://github.com/paritytech/parity) and [in the roadmap in Quorum](https://github.com/jpmorganchase/quorum/wiki/Product-Roadmap)

**Comment by AlastriaSertec** [comment]
Starting from the basis that you have to upload a file to be considered in the network, having to download another from git should not be a problem, what can give more problems is the frequency of updating that git file, who and when they publish. Apart from that, if it can be solved, there would be no problem.

> That is something already available in Parity

I've looked a little over Parity as you suggest, and it seems that it has a notification system, however to implement this here, it would need quorum to already have it, but well, as i said, i only looked a little...

**Comment by AlastriaSertec** [comment]
> Someone trusted enough to hace commit access to the repository each 6M blocks?

So then let them talk
