### ISSUE TITLE
Fail node startup.sh on Ubuntu 18 [With patch to make it work]

### ISSUE THREAD

**Issue by kikoncuo** [alastria/alastria-node#262]
##### Error:
```constellation-node: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory```
##### Reason:
Bootstrap downloads the latest version, version 18 is not the latest and therefore it can't find it. It should download a fixed version not latest.
##### Patch:
Since backwards compatibility is not broken, we can just copy the file with version 18 at the end.
Find latest version:
```ls -a /usr/lib/x86_64-linux-gnu/ | grep 'libsodium' ```
Rename file:
```sudo cp /usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0 /usr/lib/x86_64-linux-gnu/libsodium.so.18 ```

**Comment by kikoncuo** [comment]
This seems to be done with most libraries, we will encounter more problems like this as things go on we should change the libraries so they download to an specific version, with some time I could make a PR

**Comment by esanchma** [comment]
In the case of libsodium, libsodium18 was removed from the official repositories in favor of libsodium23. And a libsodium18 shared library is a hard dependency of constellation (which is provided in a binary bundle by JP Morgan). Both versions share the same symbols and can be used, but constellation will still output a warning if you are using libsodium23

What we do in the bootstrap is to check whether the constellation dependency is satisfied by the current system (https://github.com/alastria/alastria-node/blob/develop/scripts/bootstrap.sh#L70). If it's not, we copy libsodium back to its place. 

We have used that script successfully in Ubuntu 16.04, Centos 7 and Red Hat 7. However, distribution repositories change all the time, making the installation a moving target.

We intend to add tests to the installation in travis-ci at some point, and of course, PR are welcome.

**Comment by kikoncuo** [comment]
Mmmm seems weird then, bootstrap worked correctly, version 23 was installed, but when executing init.sh it looked for version 18 and failed, no warning.
A hard coded renaming of the file looks horrible but fixes the problem, since JP don't seem very active, would you consider that a reasonable fix?

**Comment by esanchma** [comment]
Yes, that fixconstellation hack is not a future-proof solution, and constrains us to a fixed architecture and directory layout (which, I guess, is different for Ubuntu 18). Although we could add branches and special cases for new distro releases, it has run its course, and it's time for a better approach.

The constellation sources are available in Haskell. I guess we could follow the steps in https://github.com/jpmorganchase/constellation/blob/master/README.md , install `stack` and compile constellation against the local libsodium. It will be easier than managing what-libsodium-version-points-to-what by ourselves.

I think it could be a good first patch. @kikoncuo thoughts?

**Comment by marcossanlab** [comment]
Good point, but compile constellation may take a lot of time. 

This approach may have a sense if we provide a Docker image built from the sources.

In addition, this makes sense if in addition to switching to docker images, our official documentation migrates to be deployed and configured with Docker, everything would be much easier for everyone.

What do you think?

**Comment by esanchma** [comment]
The bootstrap already takes a lot of time... @marcossanlab , it was my understanding that Docker was an option but not a hard requirement. You intend to make Alastria a Docker-only thing?

**Comment by marcossanlab** [comment]
Not really!

The first versions of the scripts generate the binary of the constellation from the sources and it has other problems likes compilation time, environment hard to configure. 

In our scenario, that constellation is optional, we can make another script. This script makes the bootstrapping and builds it and remove it from bootstrap.sh.

Problems with obsolete libraries will not solve this approach (generate a docker image from a specific Linux image yes).

With Docker, if we need to configure a new version of the operating system, we will only have to choose a reference docker image and make it work with the appropriate dependencies.

And the maintenance of the scripts would be carried out during the generation of the images of the nodes.

Upgrade versions of Quorum and Constellation may be as simple as download the latest image maintaining the `~/alastria/data` folder in a persistence volume.
