### ISSUE TITLE
Límites en los Security Groups de AWS

### ISSUE THREAD

**Issue by magranero** [alastria/alastria-node#268]
Según la [documentación de AWS](https://aws.amazon.com/es/premiumsupport/knowledge-center/increase-security-group-rule-limit/), estamos al límite de llegar al tope de reglas para controlar las IPS. Hay un límite de 5 grupos y un máximo de 50 por grupo.

**Comment by magranero** [comment]
Determinados puertos: 9000 y 21000 solo deberían tener que ser visibles desde los nodos, y como no conforman una subred, se trata de reglas independientes y AWS las contabiliza como tal. Tenéis todo puesto como origen any? (siendo así no habrá problema en los límites pero si en la defensa de la red)

**Comment by esanchma** [comment]
Los puertos 9000 (constellation) y 21000 (geth) son puertos con tráfico P2P, y el puerto 8443 (alastria-monitor) es de gestión. Esos 3 deben estar con origen 'any'. Tanto constellation como alastria-monitor usan TLS 1.2, y geth usa su propio protocolo, RLPx.

El puerto 22 por supuesto a vuestro criterio, y el puerto 22000 es al que se van a conectar vuestras aplicaciones y debe ser privado.

**Comment by marcossanlab** [comment]
En todo caso, si queréis gestionar en corto el puerto de constellation (que al fin y al cabo va a recibir transacciones privadas entre socios) lo puedes gestionar y permitir el tráfico únicamente con los socios con los que interactúes.

El puerto 21000, en este momento es mejor utilizar un any que ningúna otra cosa ya que constantemente se están añadiendo nodos, aunque, con la integración en los BootNodes, esto puede cambiar a permitir el tráfico a un conjunto de estos nodos y son estos, los que dirigen el tráfico.

Por último, el tráfico al puerto 22000 lo puedes:
1. Restringir completamente desde fuera y utilizarlo únicamente desde tu organización.
2. Publicar el puerto.

Como parte de esto último, estamos estudiando cómo definir un conjunto de reglas de capa 7 (permitiendo el tráfico sólo a lo que realmente podemos atacar) y una cobertura TLS al estilo de infura (en estudio por el grupo de plataforma).

**Comment by iasinDev** [comment]
Hola, el que constatemente se añadan nodos no es un problema, yo lo tengo scripteado de forma que cada vez que me actualizo el fich de nodos con los que hablar por awscli actualizo mis reglas de firewall de forma automatizada pero sí que tenían en mente el problema que comenta @magranero de alcanzar el límite de AWS, entonces si se tiene en cuenta la futura solución que dices @marcossanlab genial!
