### ISSUE TITLE
genesis.json - Include byzantium for calling calls between contracts

### ISSUE THREAD

**Issue by alexvinas** [alastria/alastria-node#278]
The current version of the genesis.json does not include "byzantium" upgrades. At the moment, within the current network, it is not possible to establish connection between separate smart contracts. If "Byzantium Block = 0" is added to the genesis file, the issue resolves and we are able to establish a connection between separate smart contracts. 

Thank you very much for your time!

**Comment by marcosio** [comment]
Hi @alexvinas,

If we accept this modification on our genesis, the new nodes configurated for our network, will not connect to the rest.

When we put in production a new version of our net, we introduce this modification.

**Comment by esanchma** [comment]
I agree, that's what makes sense. Let's keep this issue open in the mean time.

**Comment by marcosio** [comment]
@esanchma, We create a new brach with this change and another one who make sense for a new test-net version?

**Comment by xaler5** [comment]
There is also EIP 658 (ethereum/EIPs#658) which introduce the status in the transaction receipt that can't be used without that parameter in the genesis file.

status field is really helpful in doing fallback actions depending on the transaction status without checking if the transaction is mined or using logs.

Does a switch to the new network is planned for all the nodes ?
The more nodes join Alastria the more it will be difficult to switch.
