### ISSUE TITLE
Problema al instalar nodo 

### ISSUE THREAD

**Issue by javierCaro1** [alastria/alastria-node#296]
He intentado seguir su guia de instalación de nodo regular, sin éxito. Aunque en unos días disponemos de un equipo AWS idéntico al descrito en su guia, por el momento he decidido instalar el nodo en un Pc convencional, Ubuntu 16.04, con dos procesadores, 4gb de ram y varios cientos de Gb de disco. Este pc esta conectado a Internet por medio e un Router. He abierto los puertos que indican y los he redirigido en el Router.

He creado, siguiendo su recomendación, un usuario "ubuntu" con permisos de root.

Sin embargo, al arrancar con. /start.sh tras seguir, aparentemente sin error los pasos anteriores, observo que no aparece el texto "Starting Constellation node" (en start.sh, la línea 74 termina en ENABLE_CONSTELLATION:-}). Sí indica que arranca el quorum node, pero tras "Starting monitor...", dice que se redirige la salida de error a la salida estándar. 
En el Log, se ven numerosos errores del tipo "Failed to open file" referidos a ficheros go.

¿Podrían ayudarme?

**Comment by javierCaro1** [comment]
Tenía un problema con los permisos, ahora han desaparecido los errores "Failed to open file" 
De hecho, no tengo ningún error. Sin embargo, mi nodo no aparece en el monitor de la Red

**Comment by andresag** [comment]
Hola @javierCaro1,
¿qué identidad le has puesto al nodo? ¿puedes mostrarnos _monitor.log_ y _quorum.log_?

**Comment by javierCaro1** [comment]
Le he puesto REG_Vestigia_TestNet_2_4_01 
[quorum_20181022113020.log](https://github.com/alastria/alastria-node/files/2501170/quorum_20181022113020.log)
[monitor_20181022113020.log](https://github.com/alastria/alastria-node/files/2501172/monitor_20181022113020.log)

**Comment by andresag** [comment]
El nodo está arrancado, puedes verlo [aquí](http://netstats.testnet.alastria.io.builders/).

Falta hacer el pull request con los cambios asociados a la creación de tu nuevo nodo. Puedes consultar los pasos necesarios en el [FAQ](https://github.com/netmanito/alastria-node-wiki/blob/master/FAQ_EN.md#howto-pull-request-to-alastria-node)

**Comment by javierCaro1** [comment]
Ahora comprendo mi error: el enlace de vuestra guía debe enviar al monitor de la MainNet, no de la testnet.
En un pull request ¿validáis una IP concreta? Por ahora tengo IP dinámica.

**Comment by andresag** [comment]
La IP que se añade a los archivos _permisiones-nodes_general_ y _constellation-nodes_ es la proporcionada (o detectada, si se ejecuto con auto) en el script de inicialización. Si la IP externa del nodo cambia, deberás actualizar los ficheros en cuestión y hacer de nuevo el pull request.

Échale un vistazo a los scripts init.sh y update.sh. En cualquier caso es recomendable que los nodos de la red tengan asignada una IP pública fija.
