### ISSUE TITLE
Problema al inicial el nodo

### ISSUE THREAD

**Issue by jijaen** [alastria/alastria-node#298]
#### System information
Node type: `Regular` 
Geth version: `1.8.17-stable`
OS & Version: `Ubuntu 18.04.1 LTS`

Para la instalación de un nodo regular estoy siguiendo el manual https://medium.com/@marcos_84680/e6235dea3bd8 .  Aparentemente todo parece ir bien hasta que se ejecuta el script **start** que genera la siguiente salida por consola:
 
`[*] Starting quorum node`
`[*] Monitor enabled. Starting monitor...`
`nohup: redirecting stderr to stdout`

Si visualizamos 'nohup' encontramos: 

`Incorrect Usage. flag provided but not defined: -permissioned` seguido de las instrucciones de uso de geth. 

Además de lo anterior, he observado que el **enode** que me genera el script **init** es sensiblemente de menor longitud que los que están registrados en **DIRECTORY_REGULAR.md**.  Como he indicado arriba, la versión de **geth** que tenía previamente instalada es: `1.8.17-stable`.  ¿Puede ser esto el problema o el S.O. `Ubuntu 18.04.1 LTS`?

**Comment by andresag** [comment]
Hola @jijaen,
¿Puedes mostrarnos _monitor.log_ y _quorum.log_?

**Comment by jijaen** [comment]
[monitor.log](https://github.com/alastria/alastria-node/files/2511928/monitor.log)
[quorum.log](https://github.com/alastria/alastria-node/files/2511931/quorum.log)

Hola, el problema que tenía se solucionó con una instalación limpia en un Ubuntu 16.04.  Sin embargo ahora me ocurre lo siguiente al seguir el manual:
- Cuando ejecuto el script **start** obtengo:

`[*] Starting quorum node`
`[*] Monitor enabled. Starting monitor...`
`nohup: redirecting stderr to stdout``

... no aparece ninguna información sobre el **Constellation node**.

- al verificar con `ps awx | grep alastria` aparece el proceso `geth` pero **no** el de `constellation-node`.

En http://netstats.testnet.alastria.io.builders/ aparece el nodo : `REG_PayThunder_TestNet_2_8_02` creado. Aún no he hecho el `pull request` porque entiendo que hay algún problema con la instalación, ¿verdad? Adjunto logs.

Muchas gracias.

Un saludo.

**Comment by andresag** [comment]
Buenos días @jijaen,

Si deseas arrancar el nodo con Constellation debe hacerse de forma explícita al ejecutar el script.
`$ ENABLE_CONSTELLATION=true ./start.sh`
Ejecutado de esta forma debería obtener en la salida información del nodo constellation.
`[*] Starting Constellation node`
`[*] constellation node at 9000 is still starting. Awaiting 5 seconds.`
`[*] constellation node at 9000 is still starting. Awaiting 5 seconds.`
`[*] constellation node at 9000 is now up.`
`[*] resuming start procedure`
`[*] Starting quorum node`

Por lo demás, efectivamente parece que el nodo arranca correctamente ¿Puedes confirmar si el arranque con constellation funciona?

**Comment by jijaen** [comment]
Hola @andresag,
Muchas gracias por la ayuda.  Parece que está todo arrancado con constellation correctamente.

Un saludo.
