### ISSUE TITLE
Error al crear un contrato privado en Alastria

### ISSUE THREAD

**Issue by jordiescudero** [alastria/alastria-node#301]
#### System information

Network: `Alastria `

Node type: `Regular’ 

Node name: `Worldline-Bloomen`

Geth version: 1.8.15-stable

OS & Version: Linux

#### Expected behavior
Creación de un contrato privado siguiendo el ejemplo del github de quorum https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/private-contract.js

#### Behavior obtained
El contrato no se crea y sale el siguiente error:  err creating contract Error: EOF

#### Steps to reproduce the error
Descargar el fichero de test del github de quorum inicicado y ejecutar el comando : 
geth --exec "loadScript('/home/jordi/private-contract.js')" attach YOUR-NODE

#### Backtrace

Solo retorna el Error: EOF en la excepcion...

**Comment by netmanito** [comment]
Buenas tardes.
En referencia a la versión de geth, ¿Puedes confirmarme que lo que devuelve `geth version` es lo mismo que has indicado en la incidencia?
La versión de geth sobre la que trabaja Alastria y con la que tenemos constancia de que funcionan los contratos privados es la 1.7.2-stable. 
Si nos hiciesen llegar la copia del contrato que están utilizando para las pruebas podríamos intentar reproducir el problema. El archivo original de ejemplo https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/private-contract.js no funciona en alastria sin algunas modificaciones previas.
Gracias.

**Comment by jordiescudero** [comment]
Hola,
la version de geth es la siguiente : Geth/Worldline-Bloomen/v1.7.2-stable-94e1e31e/linux-amd64/go1.9.5 

Adjunto un zip con el proyecto truffle que he creado usando la guia https://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains

Gracias
[private-truffle.zip](https://github.com/alastria/alastria-node/files/2561135/private-truffle.zip)

**Comment by netmanito** [comment]
Buenos días, 
Revisando el código, vemos que estás enviando la transacción a la public-key de tu mismo nodo.

Las transacciones privadas han de ser entre 2 nodos diferentes, donde `PrivateFor` es el nodo que recibirá la transacción y que ha de ser distinto al nodo quien la envía `PrivateFrom`.

Gracias

**Comment by jordiescudero** [comment]
Hola,
he hecho pruebas con las diferentes public keys de mis otros nodos con el mismo resultado.
Running migration: 1_initial_migration.js
```
  Deploying Migrations...
  ... 0xaf56b58b89d8b4568008050f9670e5dd110ef7f57f302128831df7bad877aa25
  Migrations: 0x287c5b89ae09f79ad8fda096fdb9abb30f8004a3
Saving successful migration to network...
  ... 0xff164da52b1f18dab1e1485a1dbedf4a37c18eeb128cd51f641470ebd8245fbd
Saving artifacts...
Running migration: 2_simple_storage_migration.js
  Deploying simplestorage...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```
Gracias

**Comment by IvanSaizIOB** [comment]
Hola @jordiescudero, siguiendo la guía, ¿has conseguido realizar transacciones privadas?

**Comment by go2chain** [comment]
Buenas tardes!

Siguiendo la guía que comentas nosotros nos hemos encontrado con el mismo problema.

Gracias y saludos

**Comment by miguelmartinezinf** [comment]
Hola, 
no he seguido el procedimiento que comentáis pero he leído que truffle a veces tiene problemas al desplegar contra quorum, habeis probado a utilizar `migrate --reset`?

**Comment by go2chain** [comment]
Hola,
Contestando a @miguelmartinezinf si, hemos probado a desplegar usando `migrate --reset`, incluso añadiendo en el comando `--gasLimit 6721975 --gasPrice 0` como indican en algunas issues de truffle. Pero no funciona.

Por otra parte, aqui te dejo el truffle.js que estamos usando @netmanito:
```
module.exports = {
  networks: {
    alastria: {
      host: "172.10.1.100",
      port: 22000,
      network_id: "82584648528", // Match Alastria network id
      gas: 6721975,
      gasPrice: 0
    }
  }
};
```
Nos conectamos a nuestro nodo con una IP local porque la tenemos en la misma red. Si desplegamos el contrato de manera pública no hay problema, pero en el momento en el que intentamos poner el privateFor:[...] nos da ese error. Hemos probado a poner nuestra clave privada del nodo constellation y no funciona, también hemos probado a añadir la clave que viene en el ejemplo que poníais arriba (https://github.com/alastria/alastria-node/wiki/private_transactions_in_alastria), pero igual. ¿Conocéis alguna clave pública de un nodo que se sepa que está levantado para poder hacer una prueba de despliegue del contrato privado con dos nodos?

**Comment by netmanito** [comment]
Buenos días, las transacciones se han de lanzar desde el mismo nodo `constellation`, no pueden ser lanzadas desde otro nodo tal como indicamos en la issue #313 
Es decir, truffle debe estar instalado en el mismo nodo regular y se debe hacer desde allí la transacción contra localhost/127.0.0.1
Actualmente no es posible lanzar trx privadas firmadas fuera del nodo (sendRawTransaction), y consultando a JPMorgan nos han confirmado que de momento no es posible realizar este tipo de transacciones.
Saludos.

**Comment by miguelmartinezinf** [comment]
Buenas tardes,
Acabo de seguir todo el desarrollo y he conseguido desplegar el contrato correctamente (desde mi máquina) usando truffle.
https://alastria-explorer.councilbox.com/transaction/0xf0e03c8bee177da5fc02bc731537feed720c8f3f82997a0690076b07feb4b5bd

He probado acceder con web3 y ahi está el problema. No consigo desplegar ni acceder a el contrato. No es posible leer info del contrato ni realizar transacciones. Sale un error del tipo: `invalid json response '' " `. alguna idea?

PD: @go2chain como prueba "tonta" cambia el nombre del network por development. A veces truffle se queda atascado con cosas asi...

PD2: Creando una red privada quorum del repo oficial sí he conseguido interactuar con web3.  ¿Alastria y el repo oficial de quorum tienen las mismas versiones ?

**Comment by go2chain** [comment]
Buenos días @netmanito, comentar que hemos conseguido desplegar el contrato desde truffle y desde fuera del nodo (estando en la misma red local). El problema que nos estaba dando era porque habíamos reiniciado nuestro nodo de alastria pero no habíamos seteado la variable `ENABLE_CONSTELLATION=true` al volver a lanzar el script `./start.sh.`

Gracias @miguelmartinezinf por la ayuda pero al final no ha hecho falta.

Por otra parte, nosotros si hemos conseguido interactuar con web3 con nuestro contrato desplegado pero tienes que tener en cuenta no podrás firmar las transacciones de momento ya que la librería web3js no soporta incluir el privateFor y JPMorgan ha avisado de que no va a dar soporte por ahora!. Te dejo un enlace al github donde lo estuvimos comentando #313 

Un saludo

**Comment by netmanito** [comment]
Cerramos la incidencia ya que creemos que se han resuelto las dudas sobre los contratos privados.
Si se necesita añadir alguna información, comentadlo y la reabriremos.
Gracias.
