### ISSUE TITLE
Problema en instalación del nodo alastria.

### ISSUE THREAD

**Issue by afieherraez** [alastria/alastria-node#307]
#### System information

Network: `Arrakis | …. `

Node type: `Validator | Regular | BootNode’ 

Node name: `VAL_Alastria_TestNet_2_8_00`

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

#### Backtrace

````
[backtrace]
````

**Comment by afieherraez** [comment]
Buenos días, cuando tratamos de instlar el nodo siguiendo los pasos del documento, cuando hacemos el ./start.sh no aparece el start constellation node.

**Comment by jijaen** [comment]
Hola @afieherraez,

Si deseas arrancar el nodo con Constellation debe hacerse de forma explícita al ejecutar el script.
`$ ENABLE_CONSTELLATION=true ./start.sh`

Un saludo.
