### ISSUE TITLE
Problema con el funcionamiento de nodo regular

### ISSUE THREAD

**Issue by rdemera** [alastria/alastria-node#312]
El nodo en cuestión funcionaba correctamente desde que se creó. En los últimos días su funcionamiento no ha sido el esperado ya que lo arrancamos y funciona con normalidad al principio pero llega un momento en que el proceso geth empieza consumir recursos de CPU y memoria hasta que consume toda la memoria y se para el proceso.

Hemos intentado cambiar el ulimit en la máquina y el problema de memoria continua.

![topn](https://user-images.githubusercontent.com/43733577/48120219-d48d1e00-e271-11e8-8110-2ef80acf1d06.png)

[quorum.log](https://github.com/alastria/alastria-node/files/2556680/quorum.log)

Gracias de antemano.

**Comment by netmanito** [comment]
Buenos días, 
Podrías rellenar la información requerida en la plantilla de incidencias? La adjunto a continuación.
Gracias

#### System information

Network: `Arrakis | …. `

Node type: `Validator | Regular | BootNode’ 

Node name: `VAL_Alastria_TestNet_2_8_00`

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

#### Expected behavior


#### Behavior obtained


#### Steps to reproduce the error


#### Backtrace

````
[backtrace]
````

**Comment by rdemera** [comment]
**System information**
Network: Arrakis | ….
Node type: Regular
Node name: REG_Tribalyte_TestNet_2_4_00
Geth version: 1.7.2-stable-94e1e31e
OS & Version: Ubuntu 16.04.4 LTS 
**Expected behavior**
Correcto funcionamiento del nodo.
**Behavior obtained**
Caída del nodo pasado un tiempo debido al consumo de memoria y CPU 
**Steps to reproduce the error**
Se inicia el nodo con $ sudo ./start.sh
Pasado un tiempo el nodo cae.
**Backtrace**
[backtrace]

**Comment by xvilapueyo** [comment]
Hola,

A nosotros nos está ocurriendo lo mismo, aquí la info del sistema:

**System information**
Node type: Regular
Node name: REG_ValidatedID_TestNet_2_16_00
OS & Version: Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-1025-azure x86_64)
Geth version: 
> Version: 1.7.2-stable
> Git Commit: 94e1e31eb6a97e08dff4e44a8695dab1252ca3bc
> Quorum Version: 2.0.2-Alastria
> Architecture: amd64
> Network Id: 1
> Go Version: go1.9.5
> Operating System: linux

El log de quorum:
[quorum_20181109222201.log](https://github.com/alastria/alastria-node/files/2567853/quorum_20181109222201.log)

**Comment by marcosio** [comment]
@rdemera , @xvilapueyo hemos publicado una nueva versión del cliente Quorum y para verificar que todo va como debe ¿Sería posible que la actualizarais con el binario de esta release https://github.com/alastria/quorum/releases/tag/v2.0.2.2.Alastria_EthNetstats_IBFT?

**Comment by marcosio** [comment]
En realidad no es necesario, si queréis descargar con wget o curl el binario que se ha incluido en la release desde el nodo y sustituirlo en `/usr/local/bin`.

**Comment by rdemera** [comment]
Nos sigue sin funcionar correctamente. El proceso que hemos seguido ha sido el siguiente: Reiniciamos la máquina virtual, y restauramos el nodo a partir de las keys que teníamos guardadas.
$ git clone https://github.com/alastria/alastria-node
$ ./bootstrap.sh
$ ./init.sh backup general REG_Tribalyte_TestNet_2_4_00
$ ./update.sh
Nos sigue dando el error de fatal error: runtime: out of memory. Adjunto el log.
[quorum_20181114114624.log](https://github.com/alastria/alastria-node/files/2580681/quorum_20181114114624.log)

Así que lo intento con el binario de la release, lo sustituyó en /usr/local/bin (le doy permisos de ejecución chmod +x) . Inicio otra vez el nodo con:
$ ./start.sh
También me da error runtime: out of memory
[quorum_20181114120959.log](https://github.com/alastria/alastria-node/files/2580686/quorum_20181114120959.log)

Siempre que empieza el proceso de geth el uso de recursos (memoria y cpu) es exagerado en comparación con una ejecución normal. La memoria solo crece.

**Comment by xvilapueyo** [comment]
A nosotros sí que nos ha solucionado el comportamiento. Hemos copiado el [geth ](https://github.com/alastria/quorum/releases/download/v2.0.2.2.Alastria_EthNetstats_IBFT/geth) y de momento lleva 24h estable.

En nuestro caso la máquina tiene 16Gb de RAM.

**Comment by marcosio** [comment]
@rdemera, parece que el nodo está activo en la red, ¿Puedes verificar que el nodo es estable en este momento?

**Comment by IvanSaizIOB** [comment]
Hola @rdemera alguna novedad respecto a esta issue? ¿Puedes indicarnos el estado actual del nodo? Gracias

**Comment by rdemera** [comment]
Pues hemos intentado resolver el problema por muchas maneras pero sigue sin funcionar (actualizando con el nuevo binario, tirando el nodo y volver a levantarlo). No sigue dando el mismo error de memoria.

**Comment by JuanLuisGozaloFdez** [comment]
Al ser este un issue relacionado con Arrakis, damos por cerrado este incidente.
Por favor, si alguien tiene una incidencia con la Red Telsius de este tipo de incidencia, por favor, indicadlo en un nuevo ticket.
