### ISSUE TITLE
Parada inopinada de nodo regular AWS

### ISSUE THREAD

**Issue by javierCaro1** [alastria/alastria-node#322]
#### System information

Network: `Alastria Testnet`

Node type: `Regular’ 

Node name: `REG_Vestigia_TestNet_2_4_02`

#### System information
Instancia: REG_Vestigia_TestNet_2_4_02/v1.7.2-beta-a8fe2e92/linux-amd64/go1.9.5
Geth version: v1.7.2-beta-a8fe2e92

OS & Version: Ubuntu 16.04

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
Una vez iniciado con "./start.sh --no-monitor" el nodo debe permanecer visible y sincronizando en la página http://netstats.testnet.alastria.io.builders/ hasta ser detenido con "./stop.sh"

#### Actual behaviour
Tras varias horas, sin haber accedido a la máquina, se observa que el nodo desaparece de la lista en la página http://netstats.testnet.alastria.io.builders/ o se muestra en gris (detenido). Si se inicia con ./start.sh --no-monitor, el nodo vuelve a aparecer en la lista. El número de bloques no ha aumentado desde que se produjo la desaparición de la lista.
Se puede observar que en los ficheros log no se aprecia ningún mensaje de alerta o error.
He seguido estrictamente las instrucciones de la página https://medium.com/@daniellalorenzo/creating-and-interacting-with-a-regular-node-in-alastria-9546ba38d263. Observo que se instala una versión beta de geth, que ningún otro nodo utiliza.

#### Steps to reproduce the behaviour
Cada vez que lo incio desde "/home/alastria-node/scripts", haciendo "$ ./start.sh --no-monitor" ocurre lo mismo, aunque puede tardar un número indeterminado de horas, no superior a 10.

#### Backtrace

[quorum_20181112183714.log](https://github.com/alastria/alastria-node/files/2576175/quorum_20181112183714.log)
[monitor_20181112183714.log](https://github.com/alastria/alastria-node/files/2576176/monitor_20181112183714.log)

**Comment by javierCaro1** [comment]
Perdón. He visto en syslog que el sistema detiene el proceso geth por "Out of memory":
```
Nov 12 21:11:27 ip-172-31-32-208 kernel: [23646.584291] Out of memory: Kill process 15229 (geth) score 767 or sacrifice child
Nov 12 21:11:27 ip-172-31-32-208 kernel: [23646.590160] Killed process 15229 (geth) total-vm:4444208kB, anon-rss:3098384kB, file-rss:0kB
```
He visto este asunto en otros Issues. **Podría estar relacionado con tener abierto a cualquier IP el puerto RPC (22000)**. ¿Para qué sirve? Veo en vuestra documentación la nota "this can be internal only" ¿Qué configuración recomendáis para este puerto en el "security group" de AWS?

**Comment by marcosio** [comment]
@javierCaro1, hemos realizado una revisión y es necesario que vuelvas a realizar el bootstrap del nodo para actualizar el binario de geth.

Se ha publicado una nueva versión del cliente ayer.

**Comment by netmanito** [comment]
Hola @javierCaro1, 
¿seguís con los problemas de `Out of memory` o ya os funciona correctamente el nodo?
Gracias!

**Comment by javierCaro1** [comment]
Funciona perfectamente. Desaparecieron con la actualización del binario que nos recomendasteis. Muchas gracias por vuestra ayuda.
