### ISSUE TITLE
Nodo REG_OpenCanarias_TestNet_2_8_02 no aparece en el monitor

### ISSUE THREAD

**Issue by benitojcv** [alastria/alastria-node#324]
#### System information

Node type: `Regular’ 

Node name: `REG_OpenCanarias_TestNet_2_8_02`

Geth version: 1.7.2

OS & Version: Linux

#### Expected behavior

Hemos inicializado el nodo y se llegó a ver el el monitor, pero pasado un tiempo ha desaparecido de la lista. La máquina está operativa y con el proceso geth consumiendo el 197% de la CPU

Tenemos otros 3 nodos (con secuencias 01, 03 y 04) que sí  aparecen en el monitor.

#### Behavior obtained

Debería aparecer la máquina en el monitor.

**Comment by marcosio** [comment]
Buenas tardes,

Creeemos que es un problema asociado al cliente  quorum que está instalado en sus nodos. 

Siguiendo el guión  (update geth binary versión)[https://github.com/alastria/alastria-node/wiki/FAQ_EN#update-geth-binary-version], actualicen el nodo y vuelvan a arrancar.

**Comment by IvanSaizIOB** [comment]
Hola @benitojcv, actualizaste el cliente quorum para comprobar su correcto funcionamiento?
Gracias

**Comment by benitojcv** [comment]
Aún no. Agradecemos las instrucciones que nos habéis enviado y las tomaremos en cuanta cuando retomemos el despliegue de los nodos.

**Comment by go2chain** [comment]
Buenas tardes @benitojcv ,
Vamos a cerrar la incidencia por ahora a falta de confirmación.
En caso de que aún no funcione correctamente, la volveremos a abrir.
Muchas gracias.
Un saludo
