### ISSUE TITLE
Nodos REG_OpenCanarias_TestNet_2_8_03 y REG_OpenCanarias_TestNet_2_8_04 offline

### ISSUE THREAD

**Issue by benitojcv** [alastria/alastria-node#325]
#### System information

Node type: `Regular’ 

Node name: `REG_OpenCanarias_TestNet_2_8_02` y `REG_OpenCanarias_TestNet_2_8_03`

Geth version: `1.7.2`

OS & Version: Linux

#### Expected behavior

Los nodos deberían estar online y sincronizando la cadena de bloques.

#### Behavior obtained

Los nodos están inicializados y aparecen en el monitor, pero aparecen en estado offline. Llegaron a estar en online pero hace ya horas que siguen en offline y no avanza la sincronización.
Las máquinas están consumiendo el 200% de CPU.

**Comment by marcosio** [comment]
Buenas tardes,

Creeemos que es un problema asociado al cliente quorum que está instalado en sus nodos.

Siguiendo el guión update geth binary versión https://github.com/alastria/alastria-node/wiki/FAQ_EN#update-geth-binary-version, actualicen el nodo y vuelvan a arrancar.

Un saludo

**Comment by go2chain** [comment]
Buenas tardes @benitojcv ,
Al igual que en la incidencia #324 la cerramos a falta de confirmación.
En caso de que siga sin funcionar, la volveremos a abrir.
Muchas gracias
Un saludo
