### ISSUE TITLE
Sincronización demasiado lenta

### ISSUE THREAD

**Issue by benitojcv** [alastria/alastria-node#326]
#### System information

Node type: `Regular’ 

Node name: `REG_OpenCanarias_TestNet_2_8_01`

Geth version: `1.7.2`

OS & Version: Linux

#### Expected behavior

La sincronización debería ir más rápido

#### Behavior obtained

El nodo lleva sincronizando unas 3 horas y solo ha sincronizado 259200 bloques. A este ritmo tardaría semanas en sincronizar toda la cadena de bloques.

**Comment by marcosio** [comment]
@benitojcv , los problemas de sincronización entre nodos suelen producirse por:

* Bajos recursos de la máquina.
* Problemas de comunicaciones (latencia de red).

Entendemos que es un problema más relacionado con las comunicaciones que con los recursos de la máquina asignada.

Si el problema es de latencia, es mejor sincronizar primenro un nodo y dejar los demás en espera hastas que este sincronize.

De esta forma, conseguiremos que luego la sincronización sea mucho más rápida con el resto de los nodos.

**Comment by JuanLuisGozaloFdez** [comment]
@benitojcv, ¿Podemos dar por cerrado este ussue con la indicación que dio @marcosio?

**Comment by benitojcv** [comment]
Hola. No hemos retomado el trabajo con el nodo. No obstante, podéis cerrar el issue. Abriremos otro si se reproduce el problema cuando retomemos el trabajo.
