### ISSUE TITLE
No aparecemos en el monitor de red

### ISSUE THREAD

**Issue by afieherraez** [alastria/alastria-node#332]
Hemos decidido empezar de 0 la instalación de alastria ya que no lo conseguíamos hacer funcionar

Seguimos todos los pasos del documento y cuando hacemos el : 
./init.sh auto general REG_XXX_TestNet_2_4_01

Nos da el siguiente error: 
./init.sh: line 137: /root/alastria-node/scripts/monitor.sh: No such file or directory

No hay ningún directorio dentro de root llamado alastria-node, sólo alastria sin nada mas

**Comment by IvanSaizIOB** [comment]
Por favor podéis hacer un gitclone de alastria-node en root y probar de nuevo?
Muchas gracias.

**Comment by IvanSaizIOB** [comment]
Sí, accede al root desde la terminal haciendo por ejemplo "sudo su". A continuación desde ese directorio escribe el siguiente comando: "git clone https://github.com/alastria/alastria-node". De esta forma tendrás la carpeta alastria-node dentro de root y podrás hacer el init.sh eliminando el error que tenías anteriormente y así continuar con el proceso de instalación de vuestro nodo.
Si tienes cualquier duda me dices.
Gracias.

**Comment by afieherraez** [comment]
Muchas gracias, voy a probar.

**Comment by afieherraez** [comment]
Efectivamente lo he podido instalar así, sin embargo estamos en las mismas que antes de reinstalar,
Por defecto no arranca el nodo constellation, asi que como nos indicaron en otra incidencias hemos puesto:
ENABLE_CONSTELLATION=true ./start.sh

aparece todo arrancado sin embargo cuando pinchamos en http://52.56.86.239:3000/ para buscar nuestro nodo no aparece.

**Comment by netmanito** [comment]
Hola @afieherraez, la url a la que accedes para netstats está obsoleta, por favor, comprueba que en la url http://netstats.testnet.alastria.io.builders/ podeis ver vuestro nodo ya que debería aparecer ahí.
Coméntanos si aparece o no.
Gracias!

**Comment by IvanSaizIOB** [comment]
Hola @afieherraez, pudiste comprobar que vuestro nodo aparece en http://netstats.testnet.alastria.io.builders/ ?
Gracias!

**Comment by IvanSaizIOB** [comment]
@afieherraez cuál es el nombre de vuestro nodo que no tiene peers?

**Comment by afieherraez** [comment]
REG_AFI_TestNet_2_4_01

**Comment by netmanito** [comment]
Hola @afieherraez, parece que hay un problema en los archivos de permisionado y tu nodo aparece 2 veces con diferentes `enode`.
Puedes confirmarnos que tus datos actuales son `enode://638b48c630c7bd8838cc81b35f6f7a41e9e3107b36b3be1c79c02c6f1c1b5b80d53303e38f7152261e84a0547528539e833e62ee74c4ec4a659c3a27bf532b7d@34.244.210.133:21000?discport=0` ?
Gracias!

**Comment by afieherraez** [comment]
Donde lo verifico para no equivocarme?

**Comment by netmanito** [comment]
Hola @afieherraez, desde dentro del nodo puedes hacer `geth attach ~/alastria/data/geth.ipc` y dentro de la consola escribes  `admin.nodeInfo`.

También puedes lanzar esta petición curl que te devolverá también el enode entre otra info `curl -X POST --data '{"jsonrpc":"2.0","method":"admin_nodeInfo","params":[],"id":0}' http://localhost:22000`

Saludos

**Comment by afieherraez** [comment]
pues el  enode que me aparece es este
enode://f744b7c05366f16b0d6d6045afd6505a82d92761e81e64eec84fb41bc31cf194cbb6b379ffff3613fde103855add67f4b3243ced79dc5bf48fa9d2b97fea096f@[::]:21000"

**Comment by netmanito** [comment]
Hola, 
Este `enode` no se corresponde con los que registrásteis en los archivos de permisionado del pull request.
Deberíais revisar la configuración y realizar el pull request con los datos correctos del `enode`.

En la [wiki](https://github.com/alastria/alastria-node/wiki) podeis encontrar información de cómo realizar correctamente estas tareas. 
Saludos

**Comment by netmanito** [comment]
Hola @afieherraez, 
Habéis conseguido solucionar el problema? 
Si necesitáis más ayuda podéis preguntar en el canal de slack para que alguien del equipo os eche una mano.
Gracias!

**Comment by afieherraez** [comment]
He creado un pull request, corrigiendo el node, ¿pueden verificarlo ahora?

**Comment by afieherraez** [comment]
Buenos días, seguimos apareciendo en rojo

**Comment by netmanito** [comment]
Hola @afieherraez,
tu nodo aparece por duplicado en los archivos de configuración, es por eso que no sincroniza correctamente.
¿Puedes confirmarnos cual de los 2 enodes es el correcto?

```
permissioned-nodes_validator.json:    "enode://9081b977dab74099a79cf4aff01970892a36ef99029e2c615a30c5e29da0504e154a1ff698eeca46f2b7771bc6ffb3dbee7177dadcf5d669d440b69f30556d9f@34.244.210.133:21000?discport=0",
permissioned-nodes_validator.json:    "enode://ab7bd70ce5630c49257c5882f25816d09495a4b995a4cc17e9bc241f46616ce0b9c023b136b325caaecca6d6570f7a27524bebf3ef75e76d019b0b6010af5de1@34.244.210.133:21000?discport=0",```

Gracias!

**Comment by afieherraez** [comment]
el que termina en 9f:
"enode://9081b977dab74099a79cf4aff01970892a36ef99029e2c615a30c5e29da0504e154a1ff698eeca46f2b7771bc6ffb3dbee7177dadcf5d669d440b69f30556d9f@34.244.210.133:21000?discport=0",

**Comment by afieherraez** [comment]
Buenos días, hemos desaparecido del monitor de red.

**Comment by netmanito** [comment]
Hola @afieherraez,
Puedes darnos más información?
¿El nodo tiene `peers`?, ¿Està activo? ¿Es el enode que termina en 9f, tiene otro enode?
Qué mensajes os dan los logs?
Gracias.

**Comment by afieherraez** [comment]
> admin.nodeInfo
{
  enode: "enode://9081b977dab74099a79cf4aff01970892a36ef99029e2c615a30c5e29da0504e154a1ff698eeca46f2b7771bc6ffb3dbee7177dadcf5d669d440b69f30556d9f@[::]:21000",
  id: "9081b977dab74099a79cf4aff01970892a36ef99029e2c615a30c5e29da0504e154a1ff698eeca46f2b7771bc6ffb3dbee7177dadcf5d669d440b69f30556d9f",
  ip: "::",
  listenAddr: "[::]:21000",
  name: "Geth/REG_AFI_TestNet_2_4_00/v1.7.2-stable-94e1e31e/linux-amd64/go1.9.5",
  ports: {
    discovery: 21000,
    listener: 21000
  },
  protocols: {
    istanbul: {
      difficulty: 5795596,
      genesis: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd474c",
      head: "0xf485cba630e29b762708241654babdb2d79295fb3c2d63c63ee7b5ead5d32a58",
      network: 82584648528

**Comment by afieherraez** [comment]
El nodo es ese y desde ayer no sale en: http://netstats.testnet.alastria.io.builders/

Ayer salía pero no tenía peers

**Comment by afieherraez** [comment]
ahora mismo estamos saliendo!!
