### ISSUE TITLE
¿Cómo Acceder desde una aplicación web alojada en otro servidor a un nodo de la red?

### ISSUE THREAD

**Issue by rdemera** [alastria/alastria-node#336]
Para ello se deberá habilitar CORS, lo hacemos de la siguiente manera. Editamos el script start.sh (~/alastria-node/scripts/start.sh) y añadimos la siguiente línea en "GLOBAL_ARGS"
 
rpccorsdomain=http://tudominio:puerto

Con ello ya podríamos acceder a nuestra aplicación web conectando con el nodo de la red. 

Pedimos que esta información se añada a la documentación de Alastria-Node.

https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

**Comment by IvanSaizIOB** [comment]
Hola @rdemera, ¿podrías por favor hacer una PR con los cambios que has realizado en el script start.sh? Lo revisamos y actualizamos para que toda la comunidad pueda hacer uso de ello.
Muchas gracias!

**Comment by netmanito** [comment]
Pull requested.
