### ISSUE TITLE
Error Too many open files continuado 

### ISSUE THREAD

**Issue by rdemera** [alastria/alastria-node#341]
El nodo deja de sincronizarse y el log nos muestra el error de too many open files que ya se ha identificado. Hemos intentado modificar los ficheros necesarios para aumentar el número máximo de ficheros abiertos (ulimit -n), seguimos las instrucciones indicadas pero con un intervalo de 2/3 semanas el nodo vuelve a caer. 

Información del Nodo:
Nombre: REG_Tribalyte_TestNet_4_4_01
Quorum Version: 2.0.2-Alastria
Características de HW: 4 Cores, 4Gb Memoria Ram, 100Gb de HDD)
Ubuntu 16.04.5 LTS
Hosting: Gigas.com

Adjuntamos las imagenes de los ficheros modificados, para ver si hay algún posible fallo o falta algo. También el último log.

![sysctl](https://user-images.githubusercontent.com/43733577/49441601-4f8d1a00-f7c7-11e8-842c-b7503aa37c15.png)
![confirma](https://user-images.githubusercontent.com/43733577/49441606-5451ce00-f7c7-11e8-98a6-53b36690ebb2.png)
![limits](https://user-images.githubusercontent.com/43733577/49441607-587deb80-f7c7-11e8-98e1-42d164b56f1f.png)
![commonsession](https://user-images.githubusercontent.com/43733577/49441612-5b78dc00-f7c7-11e8-8d08-9284455991f8.png)

[quorum_20181127203619.zip](https://github.com/alastria/alastria-node/files/2643890/quorum_20181127203619.zip)

**Comment by netmanito** [comment]
#312

**Comment by rdemera** [comment]
Hemos probado aumentar más el ulimit, el último valor que le dimos fl.file-max = 231072,  el error de Too many open files sigue ocurriendo. Es cierto que está ahora ocurre en intervalos más largos, pero al final sigue ocurriendo.

![common-session](https://user-images.githubusercontent.com/43733577/51734637-6ba18f00-2085-11e9-8e55-f681a694c238.png)
![limits-conf](https://user-images.githubusercontent.com/43733577/51734638-6ba18f00-2085-11e9-9b47-43c606890d6d.png)
![sysctl-conf](https://user-images.githubusercontent.com/43733577/51734639-6c3a2580-2085-11e9-8a8b-eeeec2e8a5b1.png)

Añadimos el último log:
[quorum_20190115131718.zip](https://github.com/alastria/alastria-node/files/2795300/quorum_20190115131718.zip)

**Comment by JuanLuisGozaloFdez** [comment]
Hola. Deberias probar bajo Telsius

**Comment by rdemera** [comment]
Hola, no sabiamos que ya estaba disponible la red Telsius. Probaremos a crear un nuevo nodo y probar, gracias.
