### ISSUE TITLE
What about shell scripts writing new nodes on top?

### ISSUE THREAD

**Issue by tsteinmetz-sap** [alastria/alastria-node#349]
Hi,

I've noticed that the Alastria shell scripts automatically add the new node-information (like enode and ips) to the very bottom of the various files (static-nodes.json, permissioned-nodes_general.json, ...).

As it comes to merge-conflicts because of the colon "," always added to the last line of the old version, wouldn't it make more sense to add the new nodes on the very top of each file? Thus, only a line-addition is registered in Git and automatic merge should be possible?

Cheers,
Thomas

**Comment by netmanito** [comment]
Hi @tsteinmetz-sap, 
Thanks for your proposal.
The are changes in the way we generate these files in the new TestNet **Telsius** version that will be deployed very soon, and we believe the issues you say will not appear again.
Kind Regards
