### ISSUE TITLE
Start.sh clean seems to be executed without using a parameter

### ISSUE THREAD

**Issue by tsteinmetz-sap** [alastria/alastria-node#358]
Network: Arrakis
Node type: Regular
Node name: REG_SAP_2_4_00
Geth version: 1.7.2-beta
OS & Version: Ubuntu 18.04.1 LTS

#### Expected behavior
start.sh should only start the server without cleaning the whole server and initializing it new. At least, a prompt should ask the user if the server really should be wiped clean.

#### Behavior obtained
Somehow, our server's config was deleted by calling the start.sh script (without any parameters). I've checked in the .bash_history and ./start.sh was never called with a parameter.

#### Steps to reproduce the error
So far, I've not been able to reproduce it. I'm not familiar with shell scripts - could there be a race condition in which the clean script is automatically called? Maybe something to do with empty arguments or other external environment variables?
It also could be an Ubuntu 18 related error ... 

#### Workaround
I've commented out the cleanup code in start.sh in order not to have our server initialized again and again (syncing the currently 17+ Million blocks...).

**Comment by netmanito** [comment]
Hi @tsteinmetz-sap, 
thats a very strange behaivour, we've not been able to reproduce it.
`start.sh` script is very simple and `clean` option has to be introduced as a *flag* .
Will keep this open and if someone can test or gets the same problem we'll look deeper at it.
Thanks!
