### ISSUE TITLE
Regular node has not HISTORICAL block data

### ISSUE THREAD

**Issue by Ferparishuertas** [alastria/alastria-node#364]
#### System information

Network: `ALL `

Node type: `Regular’ 

Node name: `XX`

#### Expected behavior

In one of our use cases at IObuilders, for systems concilliation processes, we need to know given contract data at a given block number. When testing with alastria, either in telsius or arrrakis, we found the following problem, when accesing old historical block data.

 Error: Returned error: missing trie node

Following the suggestions at the  following lines, we deleted the chaindata folder and re-initialized our telsius node to resync all date with --gcmode=archive

https://ethereum.stackexchange.com/questions/54737/accessing-older-blocks-from-geth-returned-error-missing-trie-node-94d34
https://github.com/ethereum/go-ethereum/issues/16123

We suggest to introduce an alastria command line flag to be able to allow a person, to have a full archive node, without pruning, to get all historical data.

**Comment by Ferparishuertas** [comment]
Any news about this topic?

Any feedback is very welcome

**Comment by NachoDeLaVega** [comment]
Funcionalidad añadida en la rama Telsius
https://github.com/alastria/alastria-node/pull/403
