### ISSUE TITLE
Nodo no encuentra peers

### ISSUE THREAD

**Issue by lales12** [alastria/alastria-node#369]
Hola.

Estamos configurando un nodo en alastria REG_SIGNATURIT-QA_TestNet_00, ya tenemos echo el pr y actualizado. El problema es que el nodo sigue sin encontar peers.

**Comment by andresag** [comment]
Hola @lales12 ,

Una vez hecho el PR se ha de esperar a la actualización de alguno de los nodos validadores para que añadan los nuevos nodos a sus ficheros de permisionado. Estas actualizaciones suceden de manera planificada cada 72h.

**Comment by lales12** [comment]
Gracias Andres por la información.

**Comment by go2chain** [comment]
Hola @lales12  ,

Veo que en el monitor ya aparece verde y con 9 peers conectado.

Por lo tanto, voy a cerrar la issue. Si pasa cualquier cosa, háznoslo saber.

Un saludo!
