### ISSUE TITLE
Update script failing? My node does not sync

### ISSUE THREAD

**Issue by dgrmunch** [alastria/alastria-node#374]
#### System information

Network: `Arrakis `

Node type: `Regular’ 

Node name: `REG_DOCUTEN_TestNet_4_8_00`

Geth version: 

Geth
Version: 1.7.2-stable
Git Commit: 94e1e31eb6a97e08dff4e44a8695dab1252ca3bc
Quorum Version: 2.0.2-Alastria
Architecture: amd64
Network Id: 1
Go Version: go1.9.5
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Ubuntu 16

#### Expected behavior

The node should be green and with activity  in the monitor: http://netstats.testnet.alastria.io.builders/

#### Behavior obtained

The node is still in red in the monitor: http://netstats.testnet.alastria.io.builders/

#### Steps to reproduce the error

./update.sh

````
[*] Updating base code
Already up-to-date.
[*] Updating static-nodes
[*] Updating permissioned-nodes
[*] Restarting node
[*] Starting quorum node
[*] Monitor enabled. Starting monitor...
nohup: redirecting stderr to stdout
````

#### Backtrace

````

ps aux | grep sh

geth --datadir /home/enxendra/alastria/data --networkid 82584648528 --identity REG_DOCUTEN_TestNet_4_8_00 --permissioned --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --rpcport 22000 --port 21000 --istanbul.requesttimeout 10000 --ethstats REG_DOCUTEN_TestNet_4_8_00:bb98a0b6442386d0cdf8a31b267892c1@netstats.testnet.alastria.io.builders:80 --verbosity 3 --vmdebug --emitcheckpoints --targetgaslimit 18446744073709551615 --syncmode full --vmodule consensus/istanbul/core/core.go=5

````

**Comment by go2chain** [comment]
Hola @dgrmunch ,

Veo que en el monitor ya aparece verde y con 7 peers conectado.

Por lo tanto, voy a cerrar la issue. Si pasa cualquier caso, háznoslo saber.

Un saludo!
