### ISSUE TITLE
Unexpected fluctuations in block propagation time

### ISSUE THREAD

**Issue by bogdanstirbu** [alastria/alastria-node#377]
#### System information

Network: `Arrakis`

Node type: `Regular’ 

Node name: `REG_Accenture_TestNet_2_8_00`

Geth version:
`Geth Version: 1.7.2-stable
Git Commit: 94e1e31eb6a97e08dff4e44a8695dab1252ca3bc
Quorum Version: 2.0.2-Alastria
Architecture: amd64
Network Id: 1
Go Version: go1.9.5
Operating System: linux
GOPATH=/home/ubuntu/alastria/workspace
GOROOT=/usr/local/go`

OS & Version: `Ubuntu 16.04 64bits`

#### Expected behavior
Block propagation time between 0ms and 150ms

#### Behavior obtained
Unexpected fluctuations in block propagation time between 0ms and 11s

**Comment by go2chain** [comment]
Buenas tardes @bogdanstirbu ,
Parece que fue algo momentáneo y que el funcionamiento ahora es correcto.
Cierro la incidencia y si vuelve a ocurrir la re-abrimos!
Muchas gracias
