### ISSUE TITLE
Truffle is not deploying Contract

### ISSUE THREAD

**Issue by Knowledge91** [alastria/alastria-node#398]
#### System information

Network: `Arrakis `

Node type: `Regular’ 

Node name: `REG_DIRK_TestNet_2_4_00`

Geth version: `geth version 1.8.21-stable`

OS & Version: OSX

#### Expected behavior
`truffle migrate --network alastria` deploys Smart Contract.

#### Behavior obtained
`truffle migrate --network alastria` is not responding (since 10min)

#### Steps to reproduce the error
1. Prepare contract in truffle contracts
2. setup `truffle.js` like
```
module.exports = {
  networks: {
    alastria: {
      host: '18.203.238.47',
      port: 22000,
      gasPrice: 0,
      network_id: 1140,
    },
```
3. execute `truffle migrate --network alastria`

#### Backtrace

````
[backtrace]
````

P.S. I am following https://medium.com/@daniellalorenzo/creating-and-interacting-with-a-regular-node-in-alastria-9546ba38d263. I can open the **geth console** with `geth attach`. Furthermore I can unlock my account and perform transactions.

**Comment by go2chain** [comment]
@Knowledge91 
Could you tell me the version of truffle and solidity that you are using?
Thank you

**Comment by go2chain** [comment]
@Knowledge91 
As you can see in this "issue" in the truffle official repository. It seems that they have not yet supported the latest versions of quorum and solidity. For now you can try solidity <0.5 and truffle <5
Thank you.

**Comment by Knowledge91** [comment]
Yay. Problem Solved.

I downgraded to:
Truffle v4.1.15 (core: 4.1.15)
Solidity v0.4.25 (solc-js)
