### ISSUE TITLE
Conectarse al geth client mediante websockets

### ISSUE THREAD

**Issue by lales12** [alastria/alastria-node#452]
Buenos dias.

Tengo la integración con el nodo de alastria mediante httpProvider. Pero he estado intentando hacerlo mediante websockets y no me lo permite. Imagino que el puerto sera distinto al 22000 que es el que usamos para http. Habéis echo alguna integración mediante websockets?

Un saludo.

**Comment by andresag** [comment]
Hola @lales12 ,
Los nodos de Alastria arrancan con la API RPC por http (flag **--rpc**) habilitada por defecto, pero no mediante websockets (flag --ws) [Ver geth [Command Line Options](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options)]. Si necesitas conexión por websockets puedes intentar modificar manualmente el arranque del nodo para incluir dicha opción.

**Comment by go2chain** [comment]
Buenas @lales12 ,
Te dejo este enlace donde un socio del consorcio explica como lo han hecho. Espero te sirva.
https://tech.tribalyte.eu/blog-websockets-red-t-alastria
Además, cierro la issue a menos que tengas más dudas o necesitas reabrirla.
Un saludo
