### ISSUE TITLE
MainNet de Alastria

### ISSUE THREAD

**Issue by dvgoyeneche** [alastria/alastria-node#514]
¿Existe alguna forma de unirse a la mainNet de Alastria? Leyendo la documentación online sólo veo posibilidad de unirse a la testnet.

Saludos

**Comment by JuanLuisGozaloFdez** [comment]
hola. dvogyeneche. Para unirse a la red Alastria, que es permisionada-publica, debes ser uno de los socios de la Asociación. Por favor, indicame a qué empresa representas para poder indicarte siguientes pasos.
