### ISSUE TITLE
Publicar puerto 22000

### ISSUE THREAD

**Issue by dvgoyeneche** [alastria/alastria-node#555]
Hola,
Únicamente podemos conectarnos a la consola del geth (puerto 22000) desde el propio contenedor de docker, es como si el puerto 22000 de la máquina física no respondiera.
¿cómo podemos hacer accesible el puerto 22000 del contenedor al resto de la red?

Saludos

**Comment by andresag** [comment]
Hola @dvgoyeneche,

La instalación con docker incluye por defecto la herramienta [Alastria Access Point](https://github.com/alastria/alastria-access-point). La API RPC se expone (y se filtra) por medio de dicha herramienta. Échale un vistazo a la info del repositorio, pero fundamentalmente son 3 cosas a tener en cuenta:
* La API RPC en remoto es accesible en: http://<NODE_IP>/rpc
* Sólo están disponibles las familias: eth, net y web3
* Access Point funciona por defecto en modo whitelist, debes [permitir manualmente](https://github.com/alastria/alastria-access-point#tools) las IP que requieran acceso al nodo

**Comment by dvgoyeneche** [comment]
Ok, entiendo que el Access point viene dentro del docker de alastria-node?
¿Se debe de arrancar de alguna manera o arranca solo?

Saludos

**Comment by andresag** [comment]
Efectivamente, el Access Point viene instalado por defecto, y se arranca conjuntamente con alastria-node al iniciar el nodo.
Un saludo.

**Comment by dvgoyeneche** [comment]
De acuerdo, ahora bien, cómo configuramos las ips permitidas? Dentro del docker de alastria-node no localizamos allow-ip.sh

**Comment by go2chain** [comment]
Buenas @dvgoyeneche ,
Te dejo un enlace al repositorio de Alastria-Access-Point https://github.com/alastria/alastria-access-point
Aquí, podrás ver la configuración y los diferentes scripts que se pueden utilizar.
Respecto al script de allow-ip.sh se encuentra en un volumen que se monta en la carpeta donde se ejecuta el docker (en tu máquina host). Se deberían crear dos carpetas:

- alastria/: Contiene la información de tu nodo (claves, constellation...) y la chain.
- alastria-access-point/: contiene la información del access-point junto con sus scripts.

Espero sirva de ayuda. Cierro la issue, en caso de que sigas teniendo dudas puedes volver a abrirla! 
Gracias y un saludo.

**Comment by dvgoyeneche** [comment]
He hecho lo que mencionais pero sigo sin poder acceder desde una máquina de la misma subred que nuestro nodo alastria a la consola del geth

**Comment by dvgoyeneche** [comment]
Lo que busco es, desde mi máquina por ejemplo, lanzar transacciones al nodo de alastria para que así pasen a la blockchain

**Comment by andresag** [comment]
Hola @dvgoyeneche!
La conexión a la consola (geth attach) no está permitida por el Access Point mediante http, ni siquiera desde equipos en la misma subred. Esto no impide desplegar contratos o lanzar transacciones contra ese nodo en remoto, siempre que las operaciones a realizar pertenezcan a las 3 familias permitidas por el filtro (web3, eth y net).
Dejo enlace a un artículo de @garaujoriestra donde explica el proceso de despliegue de un SC con las peculiaridades de un nodo de las red T con Access Point activo.

**Comment by dvgoyeneche** [comment]
Gracias Andrea, ¿dónde puedo leer el articulo?

**Comment by andresag** [comment]
Perdona, tenía un error en el enlace, ya he editado.
https://medium.com/babel-go2chain/como-desplegar-un-smart-contract-contra-la-red-t-de-alastria-56939034e884

**Comment by dvgoyeneche** [comment]
Perfecto, muchas gracias, puedes cerrar el hilo

Saludos
