### ISSUE TITLE
Verify Smart Contract in Block Explorer

### ISSUE THREAD

**Issue by victormunoz** [alastria/alastria-node#599]
It would be interesting to add the feature to verify an smart contract and show the source solidity code of the verified contracts in the contract address page.
(such as ethrescan does)

**Comment by carlosalvarezrivas** [comment]
Hi Victor, you dare to make the modification in the blockexplorer?

We could contact councilbox who are putting a blockexplorer in case they want to incorporate this function that the etherscan blockexplorer has.
