### ISSUE TITLE
Issue with deploying the node in some specified ports

### ISSUE THREAD

**Issue by angcar** [alastria/alastria-node#601]
Hi,

We are deploying the regular Alastria node in our Docker-based container environment.

We already have some of the ports specified in the file " alastria-node/docker/general/init.sh ", such as 443, 80 or 9000.

We would like to know if it is possible to change some of these ports for the deployment of the node or if it would cause any problems.
If so, would it simply be to change the ports in the indicated file or would some other intervention be necessary?

Thank you very much.
Best regards,
Ángel.

**Comment by go2chain** [comment]
Hi @angcar ,

It would be possible to change the ports. Specifically 80 and 443 refer to the alastria-access-point, you can see this repository with all its configuration and you should change it inside your node container where the nginx is launched with the default white lists.
https://github.com/alastria/alastria-access-point

Regarding port 9000, this is only used for private transactions with constellation, in case you want/need to use a different port on your host machine but redirect it into the docker on 9000.

I hope it helps, I close the issue and in case you need more information you can reopen it.

Thank you very much.
