### ISSUE TITLE
Añadir white list a constellation

### ISSUE THREAD

**Issue by marcossanlab** [alastria/alastria-node#62]
En el fichero constellation.conf se añade ipwhitelist con lo mismo que othernodes.

Hay que modificar los ficheros start.sh y restart.sh.

**Comment by marcossanlab** [comment]
Ayuda de la línea de comandos:

$ constellation-node --help
constellation-node: user error (unrecognized option `--help'
. Usage: constellation-node [OPTION...] [config file containing options]
(If a configuration file is specified, any command line options will take precedence.)
  --url[=URL] URL for this node (what's advertised to other nodes, e.g. https://constellation.mydomain.com/)
  --port[=NUM] Port to listen on for the public API
  --socket[=FILE] Path to IPC socket file to create for private API access
  --othernodes[=URL...] Comma-separated list of other node URLs to connect to on startup (this list may be incomplete)
  --publickeys[=FILE...] Comma-separated list of paths to public keys to advertise
  --privatekeys[=FILE...] Comma-separated list of paths to corresponding private keys (these must be given in the same order as --publickeys)
  --alwayssendto[=FILE...] Comma-separated list of paths to public keys that are always included as recipients (these must be advertised somewhere)
  --passwords[=FILE] A file containing the passwords for the specified --privatekeys, one per line, in the same order (if one key is not locked, add an empty line)
  --storage[=FILE] Storage path to pass to the storage engine
  --ipwhitelist[=IP...] Comma-separated list of IPv4 and IPv6 addresses that may connect to this node's public API
  -v[NUM] --verbosity[=NUM] print more detailed information (optionally specify a number or add v's to increase verbosity)
  -V, -? --version output current version information, then exit
  --generatekeys[=NAME...] comma-separated list of key pair names to generate, then exit
)

Seguro que se puede modelizar en el fichero de configuración en vez de en la línea de comandos.

**Comment by arochaga** [comment]
El --ipwhitelist de constellation no resuelve el problema de evitar que "nodos externos" se conecten a la red. De la documentación de Constellation _"**Each node exposes an API which allows the user to send a payload** to one or more public keys. That payload will be encrypted for the public key before being transferred over the wire to the recipient node."_ 

El --ipwitelist por tanto limita quien se puede conectar a la API de constellation pero no resuelve la conexión a la blockchain de "nodos externos". Esto parece estar dirigido a cuando más de un nodo comparten el mismo constellation.
