### ISSUE TITLE
Sincronización de horas

### ISSUE THREAD

**Issue by dvgoyeneche** [alastria/alastria-node#632]
Hola,
¿Cómo sincronizan los nodos de Alastria que están minando la hora?
¿Hay algún maestro que da la hora al resto de nodos?
Por extensión, ¿cómo lo hace ethereum si hay varios nodos con distintas horas en su reloj?

Saludos

**Comment by andresag** [comment]
Hola @dvgoyeneche,

La consistencia temporal de la cadena se mantiene mediante un timestamp introducido en la cabecera de cada bloque generado. El propio protocolo ethereum impide la validación de bloques con un timestamp inferior al bloque anterior. Sin embargo, la especificación no impone un límite superior, por lo que la comprobación para impedir generar bloques a nodos "adelantados" en el tiempo depende del algoritmo de consenso (IBFT en nuestro caso) y del cliente que estemos utlizando (geth/quorum en el caso de la red T de Alastria).

En concreto en la red T se realiza la siguiente comprobación:
```
// Don't waste time checking blocks from the future
if header.Time.Cmp(big.NewInt(now().Unix())) > 0 {
	return consensus.ErrFutureBlock
}
```

De este modo se descartan los bloques que tiene un timestamp mayor que el timestamp del anterior bloque validado + el BLOCK_PERIOD_TIME (1s). Por tanto, si uno de los nodos que mina está adelantado, cuando sea su turno de proponer bloque en la ronda de validación, serán el resto de validadores los que detecten la deriva temporal y descarten el bloque propuesto.

Para infromación más en detalle sobre este tema, ver:
https://ethereum.stackexchange.com/questions/5927/how-would-a-miner-cope-with-a-huge-block-time
https://ethereum.stackexchange.com/questions/5924/how-do-ethereum-mining-nodes-maintain-a-time-consistent-with-the-network/5931#5931

**Comment by dvgoyeneche** [comment]
Gracias por la respuesta.
Mi pregunta iba mas orientada a ¿quién marca la hora de la red?

Saludos

**Comment by andresag** [comment]
No hay una hora de red como tal. Los nodos obtienen el timestamp en local a partir de [epoch time](https://en.wikipedia.org/wiki/Unix_time) (independiente de zona horaria) y lo incluyen en su propuesta de bloque. Si dicho timestamp entra dentro del intervalo de aceptación de la mayoría de nodos validadores necesarios para alcanzar consenso, entonces se acepta la propuesta y se añade el bloque a la cadena.

En este sentido la "hora de red" vendría marcada por la hora que tengan la mayoría de los nodos validadores que participan en el consenso.

Si preguntas por el origen de la sincronización. El primer validador que arrancó la red T obtiene su hora sincronizando con los servidores de [ntppool.org](https://www.ntppool.org/es/).

**Comment by dvgoyeneche** [comment]
Ok, se puede cerrar ese hilo
