### ISSUE TITLE
actualización nodo alastria

### ISSUE THREAD

**Issue by dvgoyeneche** [alastria/alastria-node#633]
Hola,
¿es posible actualizar nuestro nodo de alastria de la version 1.8.12 a la 1.8.18 que tienen otros nodos?

saludos

**Comment by andresag** [comment]
Hola @dvgoyeneche,
Si, [aquí](https://github.com/alastria/quorum/releases/tag/v2.2.3-0.Alastria_EthNetstats_IBFT) tienes la release de quorum que incluye la versión 1.8.18 de geth.
En la wiki tienes una [guía](https://github.com/alastria/alastria-node/wiki/FAQ_EN#update-geth-binary-version) para descargar y actualizar manualmente el binario en vuestro nodo.
Saludos!

**Comment by dvgoyeneche** [comment]
Gracias, podeis cerrar este hilo.

**Comment by dvgoyeneche** [comment]
Una vez actualizado el nodo de esta forma, ¿cual es el procedimiento para pasar a la ultima version?

Saludos
