### ISSUE TITLE
transacciones privadas en alastria

### ISSUE THREAD

**Issue by dvgoyeneche** [alastria/alastria-node#642]
Hola,
¿Existe la posibilidad de como en quorum, emitir transacciones privadas a ciertos nodos? Usando el privateFor.

Saludos

**Comment by andresag** [comment]
Hola,
Si, es posible emitir transacciones privadas. Para ello, en quorum, se utiliza la herramienta [Constellation](https://github.com/jpmorganchase/constellation).
Las claves privateFor de los nodos que tienen instalado constellation puedes encontrarlas en el [directorio de nodos regulares](https://github.com/alastria/alastria-node/blob/testnet2/DIRECTORY_REGULAR.md) de la red.
