### ISSUE TITLE
Algoritmo de consenso en alastria

### ISSUE THREAD

**Issue by dvgoyeneche** [alastria/alastria-node#644]
Hola,
¿Cual es el algoritmo de consenso utilizado en Alastria? Entiendo que al existir nodos regulares y nodos validadores tiene que ser IBFT.

Por otro lado, ¿cómo se garantiza en Alastria que no se puedan unir nodos no autorizados?
Por ejemplo, si yo dispongo de un nodo autorizado en Alastria, podría dar mis datos (ip y puerto) a otro participante para que se uniera?

Gracias

**Comment by andresag** [comment]
Hola @dvgoyeneche, 

> ¿Cual es el algoritmo de consenso utilizado en Alastria? Entiendo que al existir nodos regulares y nodos validadores tiene que ser IBFT.
Efectivamente el algoritmo de consenso es [IBFT](https://github.com/ethereum/EIPs/issues/650).

> Por otro lado, ¿cómo se garantiza en Alastria que no se puedan unir nodos no autorizados?
Por ejemplo, si yo dispongo de un nodo autorizado en Alastria, podría dar mis datos (ip y puerto) a otro participante para que se uniera?
En cuanto a la primera parte, existen dos procesos. Una primera comprobación técnica sobre la petición de adhesión de un nuevo nodo al permsionado a través este mismo repositorio. Partiendo de esa petición se genera un proceso administrativo que comprueba que el solicitante pertenece a la organización y tiene permitido añadir un nuevo nodo a la red.
Respecto a la segunda pregunta, no sé si entiendo bien a qué te refieres. Si autorizas el acceso a vuestro nodo, los usuarios autorizados si que podrían interactuar con la chain a través de él, esto es normal en determinados casos de uso.
