### ISSUE TITLE
Error en invocación a nodo regular

### ISSUE THREAD

**Issue by sistemasamtega** [alastria/alastria-node#698]
Ola,

Desde el grupo de soporte están lanzando peticiones contra el nodo regular y obtienen el erorr **invalid host specified**

No es en principio un problema de conectividad ya que desde el servidor que hacen la llamada es accesible el nodo por el puerto 22000

Aunque el nodo tiene publicado al exterior el puerto 22000, como se está invocando en red interna el acceso se realiza por la IP de intranet del nodo de blockchain al puerto 22000

**Comment by andresag** [comment]
Hola @sistemasamtega,
¿La instalación del nodo la habéis hecho manual o con docker?

**Comment by sistemasamtega** [comment]
Ola, 

La hicimos manual. Visto en foros por el mismo error han añadido en el arranque --rpcvhosts=stg-blockchain-0001.xunta.local

**Comment by sistemasamtega** [comment]
Se procede al cambio y la respuesta ya es 
correcta
