### ISSUE TITLE
Nodo sin peers

### ISSUE THREAD

**Issue by dlanda-tecnalia** [alastria/alastria-node#749]
Desde hace unas 24 horas el nodo regular de Tecnalia ha dejado de sincronizarse intermitentemente sin haber hecho ningún cambio en él. Actualmente lleva 11 horas desincronizado según el portal de Alastria Network Status. El nodo se creó hace aproximadamente 1 mes y ha estado funcionando correctamente hasta ahora.

La causa parece ser que no tiene peers, en este tiempo que ha funcionado correctamente nunca ha tenido más de 2 peers simultaneos. Hemos modificado manualmente /alastria-node/docker/general/alastria/data/static-nodes.json incluyendo datos de nuevos nodos sacados de https://raw.githubusercontent.com/alastria/alastria-node/f0bb551772ccce4b267c870d58cc62dbc183e284/DIRECTORY_REGULAR.md y hemos reiniciado el nodo pero la lista de peers sigue estando vacía.

Como información adicional que no se si está relacionada, en los logs del contenedor se muestra

```
WARN [07-07|10:02:16.404] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-07|10:02:22.094] Full stats report failed                 err="write tcp 172.17.0.2:46746->185.180.8.152:80: use of closed network connection"
```

¿Alguna idea de qué puede estar pasando o alguna indicación de como encontrar más información?

Gracias

**Comment by alejandroalffer** [comment]
No han habido PRs recientes, y el enode que tenemos documentado, 4e0a829bb0df3ccec209d192c1e49cc714d4c6f4dc9151248ebc640cfca8bacce81da95a725e291d207d6af62c8cddf6f66fd3a670becbd7886749b448d79579, efectivamente, está en data/regular-nodes.json

He comprobado tcp/udp/21000 y está abiertos, y el log es similar al que aparece en los nodos regulares que están por ser autorizados en los Bootnodes

Desde geth, comprobad con 'admin.nodeInfo' que no ha cambiado el node, y a través de 'admin.peers' la situación de sincronización, mientras lo movemos en el grupo core

**Comment by alejandroalffer** [comment]
Por favor, actualiza tu repo a través del comando "alastria-node/scripts/update.sh", en "/root" dentro del contenedor, para asegurarnos de que tienes las últimas versiones de nodos validadores y boot

**Comment by dlanda-tecnalia** [comment]
admin.nodeInfo me devuelve un enode distinto al original: enode://3905f943ba5446eba164c07ab5f53a84ce17d74ec4d7591f6ec54b9d7608f57cae7cfdf946616385f59cfb5b910161a1f8520cb6f992bcc0d1ab932601205e91@127.0.0.1:21000?discport=0. 

De qué depende el valor del enode? Me extraña que haya cambiado sin haber hecho modificaciones.

Actualizo enode y hago un PR. Gracias

**Comment by alejandroalffer** [comment]
El enode se crea en el script de init.sh, que sólo debería ejecutar esta parte en una primera instalacion:

```
echo "[*] Initializing quorum"
geth --datadir ~/alastria/data init ~/alastria-node/data/genesis.json
cd ~/alastria/data/geth
bootnode -genkey nodekey
ENODE_KEY=$(bootnode -nodekey nodekey -writeaddress)
if [ ! -f ~/alastria-node/data/keys/data/geth/nodekey ]; then
    echo "[*] creating dir if not created and set nodekey"
    mkdir -p ~/alastria-node/data/keys/data/geth
    cp nodekey ~/alastria-node/data/keys/data/geth/nodekey
fi
```

Si nos puedes dar más información, intentamos buscar si es un bug en algún punto de la instalación

**Comment by dlanda-tecnalia** [comment]
Sin haber hecho ningún cambio el nodo volvió a conectar con 1 peer y se sincronizó de nuevo. Ha estado sincronizado un par de días y ahora ha vuelto a quedarse sin peers. ¿Podemos hacer algo para forzar que se conecte a otros nodos? 

Como comentaba arriba hemos modificado manualmente el **static-nodes.json** y hemos probado también **admin.addPeer** pero no funciona.

Gracias

**Comment by dlanda-tecnalia** [comment]
Hola, seguimos con el problema de sincronización. Actualmente lleva 7 horas desincronizado, por lo que parece que ocasionalmente si se sincroniza. 

Aporto la información que has pedido en la incidencia de Vestigia que parece un caso muy similar al nuestro:

user@alastria-1:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           393M  5.6M  387M   2% /run
/dev/sda1        97G   53G   44G  55% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda15      105M  3.6M  101M   4% /boot/efi
/dev/sdb1       7.8G   18M  7.4G   1% /mnt
tmpfs           393M     0  393M   0% /run/user/1000

user@alastria-1:~$ df -i
Filesystem       Inodes  IUsed    IFree IUse% Mounted on
udev             499648    418   499230    1% /dev
tmpfs            502134    599   501535    1% /run
/dev/sda1      12902400 228054 12674346    2% /
tmpfs            502134      1   502133    1% /dev/shm
tmpfs            502134      4   502130    1% /run/lock
tmpfs            502134     17   502117    1% /sys/fs/cgroup
/dev/sda15            0      0        0     - /boot/efi
/dev/sdb1        524288     12   524276    1% /mnt
tmpfs            502134      5   502129    1% /run/user/1000

> admin.nodeInfo
{
  enode: "enode://3905f943ba5446eba164c07ab5f53a84ce17d74ec4d7591f6ec54b9d7608f57cae7cfdf946616385f59cfb5b910161a1f8520cb6f992bcc0d1ab932601205e91@127.0.0.1:21000?discport=0",
  enr: "0xf894b840229a0adb431ba5544f613537653179dab909e7cd7fb7102802489e7dff9c315409bf3d80ccb7497a650244eb8555e6ac1a0c8cb118705036a2adfd8fba421d380c83636170cbca88697374616e62756c40826964827634826970847f00000189736563703235366b31a1033905f943ba5446eba164c07ab5f53a84ce17d74ec4d7591f6ec54b9d7608f57c83746370825208",
  id: "d94e041d29046c470c30bb21b87dc349944cc47474775dde627a8a171fc94532",
  ip: "127.0.0.1",
  listenAddr: "[::]:21000",
  name: "Geth/REG_tecnalia_T_2_4_00/v1.8.18-stable(quorum-v2.2.3-0.Alastria_EthNetstats_IBFT)/linux-amd64/go1.9.5",
  ports: {
    discovery: 0,
    listener: 21000
  },
  protocols: {
    istanbul: {
      config: {
        byzantiumBlock: 0,
        chainId: 83584648538,
        eip150Block: 0,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0,
        isQuorum: true,
        istanbul: {...},
        txnSizeLimit: 64
      },
      difficulty: 44314637,
      genesis: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd474c",
      head: "0xce567af66a42d516900d6cf895261659528f0cf75134099a6c2df3c829f35755",
      network: 83584648538
    }
  }
}

> admin.peers
[]

root@6d0653d08f17:~/alastria/logs# tail -n100 quorum_20200707110811.log
WARN [07-14|05:51:24.556] Full stats report failed                 err="write tcp 172.17.0.2:37916->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:51:42.778] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:51:54.603] Full stats report failed                 err="write tcp 172.17.0.2:38024->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:52:12.779] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:52:24.644] Full stats report failed                 err="write tcp 172.17.0.2:38124->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:52:42.778] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:52:54.681] Full stats report failed                 err="write tcp 172.17.0.2:38236->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:53:12.778] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:53:24.737] Full stats report failed                 err="write tcp 172.17.0.2:38340->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:53:42.778] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:53:54.779] Full stats report failed                 err="write tcp 172.17.0.2:38458->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:54:12.778] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:54:24.821] Full stats report failed                 err="write tcp 172.17.0.2:38558->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:54:42.820] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:54:54.886] Full stats report failed                 err="write tcp 172.17.0.2:38670->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:55:12.820] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:55:24.921] Full stats report failed                 err="write tcp 172.17.0.2:38768->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:55:42.821] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:55:54.946] Full stats report failed                 err="write tcp 172.17.0.2:38876->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:56:12.822] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:56:24.980] Full stats report failed                 err="write tcp 172.17.0.2:38968->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:56:42.823] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:56:55.016] Full stats report failed                 err="write tcp 172.17.0.2:39080->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:57:12.823] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:57:25.098] Full stats report failed                 err="write tcp 172.17.0.2:39180->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:57:42.824] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:57:55.429] Full stats report failed                 err="write tcp 172.17.0.2:39286->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:58:12.831] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:58:25.475] Full stats report failed                 err="write tcp 172.17.0.2:39386->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:58:42.832] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:58:55.560] Full stats report failed                 err="write tcp 172.17.0.2:39506->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:59:12.832] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:59:25.602] Full stats report failed                 err="write tcp 172.17.0.2:39598->185.180.8.152:80: use of closed network connection"
WARN [07-14|05:59:42.832] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|05:59:55.644] Full stats report failed                 err="write tcp 172.17.0.2:39724->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:00:12.834] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:00:25.683] Full stats report failed                 err="write tcp 172.17.0.2:39826->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:00:42.833] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:00:55.716] Full stats report failed                 err="write tcp 172.17.0.2:39946->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:01:12.834] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:01:25.797] Full stats report failed                 err="write tcp 172.17.0.2:40056->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:01:42.833] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:01:55.837] Full stats report failed                 err="write tcp 172.17.0.2:40166->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:02:12.834] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:02:25.870] Full stats report failed                 err="write tcp 172.17.0.2:40256->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:02:42.835] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:02:55.897] Full stats report failed                 err="write tcp 172.17.0.2:40362->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:03:12.835] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:03:25.919] Full stats report failed                 err="write tcp 172.17.0.2:40470->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:03:42.835] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:03:55.999] Full stats report failed                 err="write tcp 172.17.0.2:40576->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:04:12.835] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:04:26.052] Full stats report failed                 err="write tcp 172.17.0.2:40680->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:04:42.835] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:04:56.123] Full stats report failed                 err="write tcp 172.17.0.2:40794->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:05:12.837] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:05:26.157] Full stats report failed                 err="write tcp 172.17.0.2:40890->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:05:42.836] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:05:56.200] Full stats report failed                 err="write tcp 172.17.0.2:41006->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:06:12.837] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:06:26.255] Full stats report failed                 err="write tcp 172.17.0.2:41108->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:06:42.838] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:06:56.291] Full stats report failed                 err="write tcp 172.17.0.2:41216->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:07:12.839] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:07:26.316] Full stats report failed                 err="write tcp 172.17.0.2:41310->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:07:42.840] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:07:56.361] Full stats report failed                 err="write tcp 172.17.0.2:41420->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:08:12.840] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
INFO [07-14|06:08:22.250] Regenerated local transaction journal    transactions=52 accounts=1
WARN [07-14|06:08:26.385] Full stats report failed                 err="write tcp 172.17.0.2:41514->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:08:42.841] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:08:56.408] Full stats report failed                 err="write tcp 172.17.0.2:41612->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:09:12.842] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:09:26.481] Full stats report failed                 err="write tcp 172.17.0.2:41712->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:09:42.842] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:09:56.517] Full stats report failed                 err="write tcp 172.17.0.2:41816->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:10:12.843] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:10:26.612] Full stats report failed                 err="write tcp 172.17.0.2:41916->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:10:42.844] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:10:56.656] Full stats report failed                 err="write tcp 172.17.0.2:42026->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:11:12.845] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:11:26.700] Full stats report failed                 err="write tcp 172.17.0.2:42126->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:11:42.846] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:11:56.812] Full stats report failed                 err="write tcp 172.17.0.2:42238->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:12:12.846] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:12:26.848] Full stats report failed                 err="write tcp 172.17.0.2:42344->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:12:42.847] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:12:56.893] Full stats report failed                 err="write tcp 172.17.0.2:42460->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:13:12.847] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:13:26.919] Full stats report failed                 err="write tcp 172.17.0.2:42558->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:13:42.847] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:13:56.976] Full stats report failed                 err="write tcp 172.17.0.2:42674->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:14:12.847] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:14:27.016] Full stats report failed                 err="write tcp 172.17.0.2:42762->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:14:42.848] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:14:57.040] Full stats report failed                 err="write tcp 172.17.0.2:42864->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:15:12.848] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:15:27.080] Full stats report failed                 err="write tcp 172.17.0.2:42964->185.180.8.152:80: use of closed network connection"
WARN [07-14|06:15:42.848] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-14|06:15:57.113] Full stats report failed                 err="write tcp 172.17.0.2:43074->185.180.8.152:80: use of closed network connection"
root@6d0653d08f17:~/alastria/logs#

**Comment by alejandroalffer** [comment]
Problema similar a https://github.com/alastria/alastria-node/issues/751

Se trabaja en buscar motivo y workarround para el inicio del nodo
