### ISSUE TITLE
Nodo no sincroniza

### ISSUE THREAD

**Issue by jcarovestigia** [alastria/alastria-node#751]
Buenos días. Desde ayer, el nodo REG_Vestigia_Telsius_2_4_00 ha dejado de sincronizar. Indica 0 peers permanentemente. Otros nodos regulares de la red muestran el mismo tiempo de desconexión, por lo que supongo que podría tratarse de un problema general. ¿Hay alguna incidencia en la red?

**Comment by alejandroalffer** [comment]
Hola!

Por favor, entra en tu geth, de este modo "geth attach http://localhost:22000". Si el nodo se ejecuta en un contenedor, deberás hacer un "docker exec -it <id_contenedor> /bin/bash" para tener acceso a geth.

Dos comandos, que puedes ejecutar en la consola para darnos feedback: "admin.nodeInfo" y "admin.peers"

Esperamos tu respuesta, un saludo!

**Comment by jcarovestigia** [comment]
Muchas gracias por vuestra pronta respuesta.
Copio la información obtenida en la consola:
`admin.nodeInfo
{
  enode: "enode://95393eb154556a1adb05f18d378480fec36be2c23883f5738dfbff0c60e50313ef98deeb496de6dfb30107287d4df4917a8739972591588abcd44ac5f5903f49@[::]:21000?discport=0",
  id: "95393eb154556a1adb05f18d378480fec36be2c23883f5738dfbff0c60e50313ef98deeb496de6dfb30107287d4df4917a8739972591588abcd44ac5f5903f49",
  ip: "::",
  listenAddr: "[::]:21000",
  name: "Geth/REG_Vestigia_Telsius_2_4_00/v1.8.12-stable/linux-amd64/go1.9.5",
  ports: {
    discovery: 0,
    listener: 21000
  },
  protocols: {
    istanbul: {
      config: {
        byzantiumBlock: 1,
        chainId: 83584648538,
        eip150Block: 3,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 4,
        homesteadBlock: 2,
        isQuorum: true,
        istanbul: {...}
      },
      difficulty: 44314637,
      genesis: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd474c",
      head: "0xce567af66a42d516900d6cf895261659528f0cf75134099a6c2df3c829f35755",
      network: 83584648538
    }
  }
}
`
` admin.peers
[]
`

**Comment by alejandroalffer** [comment]
Sólo una comprobación más, para saber si es algo de vuestro nodo, o generalizado:

* hacer un "df -h" y un "df -i", para ver si se ha llenado alguna partición o los inodos
* enviarnos un "tail -n100" del log de quorum: con un "ps aux" podéis saber en que ficheros se están guardando los logs

Gracias!

**Comment by jcarovestigia** [comment]
ubuntu@ip-172-31-32-208:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           396M   31M  365M   8% /run
/dev/xvda1       97G   71G   27G  73% /
tmpfs           2.0G  176K  2.0G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/loop0       97M   97M     0 100% /snap/core/9436
/dev/loop1       98M   98M     0 100% /snap/core/9289
/dev/loop2       29M   29M     0 100% /snap/amazon-ssm-agent/2012
/dev/loop3       18M   18M     0 100% /snap/amazon-ssm-agent/1566
tmpfs           396M   32K  395M   1% /run/user/112
tmpfs           396M     0  396M   0% /run/user/1000

ubuntu@ip-172-31-32-208:~$ df -i
Filesystem       Inodes  IUsed    IFree IUse% Mounted on
udev             503155    326   502829    1% /dev
tmpfs            505621    504   505117    1% /run
/dev/xvda1     12800000 941495 11858505    8% /
tmpfs            505621      6   505615    1% /dev/shm
tmpfs            505621      5   505616    1% /run/lock
tmpfs            505621     16   505605    1% /sys/fs/cgroup
/dev/loop0        12780  12780        0  100% /snap/core/9436
/dev/loop1        12860  12860        0  100% /snap/core/9289
/dev/loop2           15     15        0  100% /snap/amazon-ssm-agent/2012
/dev/loop3           15     15        0  100% /snap/amazon-ssm-agent/1566
tmpfs            505621     18   505603    1% /run/user/112
tmpfs            505621      4   505617    1% /run/user/1000

ubuntu@ip-172-31-32-208:~/alastria/logs$ tail -n100 quorum_20200712160818.log
WARN [07-13|12:19:26.107] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:19:40.205] Full stats report failed                 err="write tcp 172.31.32.208:54406->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:19:56.108] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:20:10.263] Full stats report failed                 err="write tcp 172.31.32.208:54466->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:20:26.107] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:20:40.326] Full stats report failed                 err="write tcp 172.31.32.208:54528->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:20:56.107] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:21:10.395] Full stats report failed                 err="write tcp 172.31.32.208:54590->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:21:26.423] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:21:30.454] Full stats report failed                 err="ping timed out"
WARN [07-13|12:21:56.423] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:22:00.522] Full stats report failed                 err="write tcp 172.31.32.208:54694->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:22:26.423] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:22:30.597] Full stats report failed                 err="write tcp 172.31.32.208:54756->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:22:56.420] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:23:00.657] Full stats report failed                 err="write tcp 172.31.32.208:54816->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:23:26.424] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:23:30.725] Full stats report failed                 err="write tcp 172.31.32.208:54878->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:23:56.426] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:24:00.818] Full stats report failed                 err="write tcp 172.31.32.208:54940->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:24:26.425] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:24:30.881] Full stats report failed                 err="write tcp 172.31.32.208:55000->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:24:56.492] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:25:00.938] Full stats report failed                 err="write tcp 172.31.32.208:55062->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:25:26.492] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:25:31.002] Full stats report failed                 err="write tcp 172.31.32.208:55124->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:25:56.490] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:26:01.060] Full stats report failed                 err="write tcp 172.31.32.208:55184->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:26:26.490] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:26:31.123] Full stats report failed                 err="write tcp 172.31.32.208:55246->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:26:56.491] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:27:01.182] Full stats report failed                 err="write tcp 172.31.32.208:55308->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:27:26.491] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:27:32.163] Full stats report failed                 err="write tcp 172.31.32.208:55368->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:27:56.494] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:28:02.236] Full stats report failed                 err="write tcp 172.31.32.208:55430->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:28:26.494] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:28:32.303] Full stats report failed                 err="write tcp 172.31.32.208:55492->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:28:56.492] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:29:02.360] Full stats report failed                 err="write tcp 172.31.32.208:55552->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:29:26.491] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:29:32.419] Full stats report failed                 err="write tcp 172.31.32.208:55614->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:29:56.494] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:30:02.487] Full stats report failed                 err="write tcp 172.31.32.208:55676->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:30:26.494] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:30:32.560] Full stats report failed                 err="write tcp 172.31.32.208:55736->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:30:56.493] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:31:02.627] Full stats report failed                 err="write tcp 172.31.32.208:55798->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:31:26.495] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:31:32.706] Full stats report failed                 err="write tcp 172.31.32.208:55860->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:31:56.496] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:32:02.774] Full stats report failed                 err="write tcp 172.31.32.208:55920->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:32:26.493] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:32:32.833] Full stats report failed                 err="write tcp 172.31.32.208:55982->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:32:56.493] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:33:02.891] Full stats report failed                 err="write tcp 172.31.32.208:56042->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:33:26.496] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:33:32.972] Full stats report failed                 err="write tcp 172.31.32.208:56104->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:33:56.494] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:34:03.031] Full stats report failed                 err="write tcp 172.31.32.208:56166->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:34:26.495] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:34:33.102] Full stats report failed                 err="write tcp 172.31.32.208:56226->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:34:56.495] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:35:03.160] Full stats report failed                 err="write tcp 172.31.32.208:56288->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:35:26.498] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:35:33.223] Full stats report failed                 err="write tcp 172.31.32.208:56350->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:35:56.498] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:36:03.302] Full stats report failed                 err="write tcp 172.31.32.208:56410->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:36:26.518] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:36:33.365] Full stats report failed                 err="write tcp 172.31.32.208:56472->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:36:56.515] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:37:03.423] Full stats report failed                 err="write tcp 172.31.32.208:56534->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:37:26.515] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:37:33.938] Full stats report failed                 err="write tcp 172.31.32.208:56594->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:37:56.517] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:38:03.990] Full stats report failed                 err="write tcp 172.31.32.208:56656->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:38:26.516] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:38:34.055] Full stats report failed                 err="write tcp 172.31.32.208:56718->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:38:56.517] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:39:04.122] Full stats report failed                 err="write tcp 172.31.32.208:56778->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:39:26.520] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:39:34.195] Full stats report failed                 err="write tcp 172.31.32.208:56840->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:39:56.519] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:40:04.262] Full stats report failed                 err="write tcp 172.31.32.208:56902->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:40:26.519] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:40:34.332] Full stats report failed                 err="write tcp 172.31.32.208:56962->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:40:56.523] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:41:04.399] Full stats report failed                 err="write tcp 172.31.32.208:57024->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:41:26.520] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:41:34.451] Full stats report failed                 err="write tcp 172.31.32.208:57086->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:41:56.520] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:42:04.513] Full stats report failed                 err="write tcp 172.31.32.208:57146->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:42:26.520] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:42:34.576] Full stats report failed                 err="write tcp 172.31.32.208:57208->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:42:56.523] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:43:04.639] Full stats report failed                 err="write tcp 172.31.32.208:57270->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:43:26.524] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:43:34.713] Full stats report failed                 err="write tcp 172.31.32.208:57332->185.180.8.152:80: use of closed network connection"
WARN [07-13|12:43:56.519] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [07-13|12:44:04.780] Full stats report failed                 err="write tcp 172.31.32.208:57392->185.180.8.152:80: use of closed network connection"

**Comment by alejandroalffer** [comment]
Vamos a solicitar un cambio en un bootnode... os pediremos de nuevo repetir las pruebas

**Comment by alejandroalffer** [comment]
El mesnaje de logs es típico cuando no estás permisiado en la red, cosa que no debería pasar: he comprobado que tu enode es válido en github

**Comment by jcarovestigia** [comment]
En mayo solicitamos la admisión de un segundo nodo. No sé si tendrá relación.

**Comment by alejandroalffer** [comment]
Parece que hay un segundo nodo anunciado en "netstats", con nombre REG_Vestigia_T_2_8_01.

Podéis comprobar, de nuevo, "admin.nodeInfo" y "admin.peers" sobre este segundo nodo?

Por comprobar si existe algún conflicto entre ellos: seguimos el caso en el grupo core para solucionarlo lo antes posible

**Comment by jcarovestigia** [comment]
Sí. En ese tenemos:
> admin.nodeInfo
{
  enode: "enode://776c3a7dde1a1721490c2860729e76b1f3b9faa3c45d5d8410131880209b4f                                                                                        476973c0baa8b3b28a91bc9a3a688c7b16d84c6c277f82a92979e9b170856610b9@127.0.0.1:210                                                                                        00?discport=0",
  enr: "0xf894b840cfaff45f1bfbc472aa65d368aeb29f962a49693c275ea01c6e11448f3fa2e8                                                                                        153ba3f90b48a9b50cb7903863458f374ef1ec36579a7c62146319eb344fe7ae6f0183636170cbca                                                                                        88697374616e62756c40826964827634826970847f00000189736563703235366b31a103776c3a7d                                                                                        de1a1721490c2860729e76b1f3b9faa3c45d5d8410131880209b4f4783746370825208",
  id: "4383d0424212f862c7f9df8a21bcb2e79ad30c5c4730b77277913bdd4d14853b",
  ip: "127.0.0.1",
  listenAddr: "[::]:21000",
  name: "Geth/REG_Vestigia_T_2_8_01/v1.8.18-stable(quorum-v2.2.3-0.Alastria_EthN                                                                                        etstats_IBFT)/linux-amd64/go1.9.5",
  ports: {
    discovery: 0,
    listener: 21000
  },
  protocols: {
    istanbul: {
      config: {
        byzantiumBlock: 0,
        chainId: 83584648538,
        eip150Block: 0,
        eip150Hash: "0x000000000000000000000000000000000000000000000000000000000                                                                                        0000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0,
        isQuorum: true,
        istanbul: {...},
        txnSizeLimit: 64
      },
      difficulty: 1,
      genesis: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd47                                                                                        4c",
      head: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd474c"                                                                                        ,
      network: 83584648538
    }
  }
}
> admin.peers
[]

**Comment by alejandroalffer** [comment]
Please, contactme at Alastria Slack, at @alejandro.alfonso, to keep searching the reason. If wasn't possible, do it by email

**Comment by jcarovestigia** [comment]
Me temo que no tengo acceso al espacio de Alastria en Slack. ¿Puedes indicarme tu correo?

**Comment by alejandroalffer** [comment]
Hola! Puedes contar conmigo en alejandro.alfonso@madisonmk.com. Si prefieres, usa Teams, y podemos hablar "en vivo". Un saludo!

**Comment by alejandroalffer** [comment]
Problema relacionado con diferencias en el nodekey del "datadir" esperado en "geth/nodekey" y el enode ofrecido por el admin.nodeInfo en la consola.

Arrancando geth en modo debug, se identifica una excepción no controlada en el inicio de geth:

```
ubuntu@ServidorBC-2:~$  geth --datadir /home/ubuntu/alastria/data --networkid 83584648538 --identity REG_Vestigia_Telsius_2_8_01 --permissioned --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --rpcport 22000 --port 21000 --istanbul.requesttimeout 10000 --ethstats REG_Vestigia_Telsius_2_8_01:bb98a0b6442386d0cdf8a31b267892c1@netstats.telsius.alastria.io:80 --verbosity 4 --vmdebug --emitcheckpoints --targetgaslimit 8000000 --syncmode full --gcmode full --vmodule consensus/istanbul/core/core.go=5 --nodiscover --metrics --metrics.influxdb --metrics.influxdb.endpoint http://geth-metrics.planisys.net:8086 --metrics.influxdb.database alastria --metrics.influxdb.username alastriausr --metrics.influxdb.password ala0str1AX1 --metrics.influxdb.host.tag=REG_Vestigia_Telsius_2_8_01 --debug --keystore /home/ubuntu/alastria/data
DEBUG[07-20|10:03:34.793|geth/main.go:240] Sanitizing Go's GC trigger               percent=100
INFO [07-20|10:03:34.793|cmd/utils/flags.go:1388] Enabling metrics collection
INFO [07-20|10:03:34.793|cmd/utils/flags.go:1399] Enabling metrics export to InfluxDB
INFO [07-20|10:03:34.794|cmd/utils/flags.go:979]  Maximum peer count                       ETH=25 LES=0 total=25
DEBUG[07-20|10:03:34.794|accounts/keystore/file_cache.go:87] FS scan times                            list=155.509µs set=91.806µs diff=6.4µs
DEBUG[07-20|10:03:34.795|accounts/keystore/account_cache.go:264] Failed to decode keystore key            path=/home/ubuntu/alastria/data/IDENTITY err="invalid character 'R' looking for beginning of value"
DEBUG[07-20|10:03:34.795|accounts/keystore/account_cache.go:264] Failed to decode keystore key            path=/home/ubuntu/alastria/data/NODE_TYPE err="invalid character 'g' looking for beginning of value"
DEBUG[07-20|10:03:34.795|accounts/keystore/account_cache.go:264] Failed to decode keystore key            path=/home/ubuntu/alastria/data/nodekey   err="invalid character 'e' looking for beginning of value"
DEBUG[07-20|10:03:34.795|accounts/keystore/account_cache.go:264] Failed to decode keystore key            path=/home/ubuntu/alastria/data/passwords.txt err="invalid character 'P' looking for beginning of value"
DEBUG[07-20|10:03:34.795|accounts/keystore/account_cache.go:264] Failed to decode keystore key            path=/home/ubuntu/alastria/data/permissioned-nodes.json err="json: cannot unmarshal array into Go value of type struct { Address string \"json:\\\"address\\\"\" }"
DEBUG[07-20|10:03:34.795|accounts/keystore/account_cache.go:264] Failed to decode keystore key            path=/home/ubuntu/alastria/data/static-nodes.json       err="json: cannot unmarshal array into Go value of type struct { Address string \"json:\\\"address\\\"\" }"
INFO [07-20|10:03:34.796|node/node.go:168]                       Starting peer-to-peer node               instance=Geth/REG_Vestigia_Telsius_2_8_01/v1.8.18-stable(quorum-v2.2.3-0.Alastria_EthNetstats_IBFT)/linux-amd64/go1.9.5
INFO [07-20|10:03:34.796|ethdb/database.go:73]                   Allocated cache and file handles         database=/home/ubuntu/alastria/data/geth/chaindata cache=768 handles=524288
INFO [07-20|10:03:35.001|eth/backend.go:133]                     Initialised chain configuration          config="{ChainID: 83584648538 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 IsQuorum: true Constantinople: <nil> Engine: istanbul}"
INFO [07-20|10:03:35.003|eth/backend.go:168]                     Initialising Ethereum protocol           versions="[63 62]" network=83584648538
INFO [07-20|10:03:35.005|core/blockchain.go:272]                 Loaded most recent local header          number=27490609 hash=776488…2e6aac td=27490610 age=7mo1d9h
INFO [07-20|10:03:35.005|core/blockchain.go:273]                 Loaded most recent local full block      number=27490609 hash=776488…2e6aac td=27490610 age=7mo1d9h
INFO [07-20|10:03:35.005|core/blockchain.go:274]                 Loaded most recent local fast block      number=27490609 hash=776488…2e6aac td=27490610 age=7mo1d9h
DEBUG[07-20|10:03:35.006|core/tx_pool.go:428]                    Reinjecting stale transactions           count=0
INFO [07-20|10:03:35.006|core/tx_journal.go:114]                 Loaded local transaction journal         transactions=0 dropped=0
INFO [07-20|10:03:35.006|core/tx_journal.go:166]                 Regenerated local transaction journal    transactions=0 accounts=0
DEBUG[07-20|10:03:35.022|eth/downloader/downloader.go:1628]      Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
INFO [07-20|10:03:35.203|ethstats/ethstats.go:149]               Stats daemon started
DEBUG[07-20|10:03:35.203|node/node.go:292]                       InProc registered                        service=&{node:0xc42036bb80} namespace=admin
DEBUG[07-20|10:03:35.203|node/node.go:292]                       InProc registered                        service=&{node:0xc42036bb80} namespace=admin
DEBUG[07-20|10:03:35.203|node/node.go:292]                       InProc registered                        service="&{mu:{state:0 sema:0} cpuW:<nil> cpuFile: traceW:<nil> traceFile:}" namespace=debug
DEBUG[07-20|10:03:35.203|node/node.go:292]                       InProc registered                        service=&{node:0xc42036bb80}                                                 namespace=debug
```

Revisando el "datadir" se observa que faltan ficheros de configuración, entre ellos el genésis.json: se hace un "git clone" de repositorio "alastria-node" y se sobreescriben ficheros "*.json" necesarios para IBFT: se deja arrancado geth a la espera de reinicio de algún nodo BOOT, para ver si finalmente se inicia la sincronización
