### ISSUE TITLE
Documentación de Cakeshop-Alastria

### ISSUE THREAD

**Issue by arochaga** [alastria/alastria-node#76]
Incluir en la Wiki de alastria-node los pasos a seguir para desplegar el Cakeshop de Alastria y un link a nuestro fork.

**Comment by marcossanlab** [comment]
Se solicita revisión.

**Comment by arochaga** [comment]
Revisado e incluída compatibilidad con nginx. Por mi parte se puede cerrar el issue salvo que consideréis que se requiere revisión adicional
