### ISSUE TITLE
Posible error en init.sh

### ISSUE THREAD

**Issue by JYisus** [alastria/alastria-node#767]
En el comando init.sh del directorio scripts, en las líneas [14](https://github.com/alastria/alastria-node/blob/testnet2/scripts/init.sh#L14) y [23](https://github.com/alastria/alastria-node/blob/testnet2/scripts/init.sh#L23), se están lanzando los siguientes comandos:

```
VALIDATOR0_HOST_IP="$(dig +short validator0.telsius.alastria.io @resolver1.opendns.com > /dev/null 2>&1 || curl -s --retry 2 icanhazip.com)"
...
CURRENT_HOST_IP="$(dig +short myip.opendns.com @resolver1.opendns.com > /dev/null 2>&1 || curl -s --retry 2 icanhazip.com)"
```

De estos, en caso de que el dig funcione, no se obtiene ninguna salida, puesto que se está redireccionando a /dev/null. Dicho de otra forma, esto solo funciona cuando el primer comando falla.
He visto que en un commit anterior estaban de la siguiente forma:

```
VALIDATOR0_HOST_IP="$(dig +short validator0.telsius.alastria.io @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com)"
...
CURRENT_HOST_IP="$(dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || curl -s --retry 2 icanhazip.com)"
```
Creo que esta es la forma correcta.
Intentando lanzar un nodo, no me generaba bien la línea del enode por esto. Supongo que es por esto por lo que no he conseguido poner mi nodo (opencanarias) operativo a pesar de que se haya aceptado el pull request.

**Comment by carlosho17** [comment]
Hola,
vemos que el nodo no sincroniza
puedes decirnos si la IP de tu servidor es 34.78.176.242 ?
tienes el geth levantado ?
has instalado con docker o sobre el sistema operativo ? 

--

**Comment by JYisus** [comment]
Hola,
Sí, esa es la dirección IP, pero la incluí yo en el enode, el despliegue me dejaba ese campo dle enode vacío (por lo que comento en el issue). Tengo que volver a hacer un pull request porque probando cosas, levanté otro nodo (con diferenete enode), pero seguía teniendo el mismo error de que no me reconocía mi IP el script.
Lo estoy levantando con docker desde una VM de Google Cloud.

**Comment by carlosho17** [comment]
Hola,
ya está corregido lo que señalaste que estaba mal por cierto, en https://github.com/alastria/alastria-node/blob/testnet2/scripts/init.sh
Así que por favor haz el nuevo intento de instalar.
Entiendo que la VM de GoogleCloud tiene una IP pública y no va a haber problemas de descubrir cuál es.
Esperamos tu nueva instalación.

**Comment by JYisus** [comment]
./init.sh: command substitution: line 15: syntax error near unexpected token `2'

En el script corregido sobra un ">" en la línea 14, la línea 23 sí es correcta. Falla el script de despliegue por eso.
