### ISSUE TITLE
Integrar MongoDB en CakeShop

### ISSUE THREAD

**Issue by marcossanlab** [alastria/alastria-node#78]
Se debería poder utilizar mongodb como origen de datos de CakeShop.

Pare ello, hay que investigar cómo integrar [Kundera](https://github.com/impetus-opensource/Kundera) con Hibernate y MongoDb.

**Comment by arochaga** [comment]
Parece mejor solución utilizar Hibernate OGM (aprovechando el uso de Hibernate ORM por parte de Cakeshop)

http://docs.jboss.org/hibernate/ogm/4.0/reference/en-US/html_single/#ogm-ehcache-transactions
http://powerupcloud.azurewebsites.net/2016/05/01/connecting-to-mongodb-in-java-using-hibernate-ogm/

Incluirlo en el proyecto de Cakeshop no está siendo inmediato.

**Comment by marcossanlab** [comment]
Off-topic, definir en Cakeshop
