### ISSUE TITLE
 VM returned with error err="invalid opcode 0x1c"

### ISSUE THREAD

**Issue by jcarovestigia** [alastria/alastria-node#794]
En mi nuevo nodo me es imposible ejecutar nuevos contratos correctamente. Tras desplegarlos, los métodos parecen no tener efecto. En logs encuentro, aparentemente asociado a una ejecución, el error:  VM returned with error                   err="invalid opcode 0x1c".

Veo en google que se trata de "That opcode is a recent addition to geth in the Constantinople release." Y recomiendan cambiar el génesis (!) 

¿Qué puedo hacer?

Utilizo solidity 0.5.0. Un contrato de ejemplo que he usado para probar es:
`pragma solidity ^0.5.0;

contract Box {
    uint256 private value;

    
    // Stores a new value in the contract
    function store(uint256 newValue) public {
        value = newValue;
    }

    // Reads the last stored value
    function retrieve() public view returns (uint256) {
        return value;
    }
  
}`

**Comment by cmoralesdiego** [comment]
Buenas @jcarovestigia , ¿has seguido estos pasos?. https://github.com/alastria/alastria-node#deployment-of-smart-contracts-on-alastria-network. Saludos!!

**Comment by cmoralesdiego** [comment]
Cierro el issue porque no hay contestación desde el pasado 14 de Octubre
