### ISSUE TITLE
Problemas al arrancar un nodo regular desde 0. 

### ISSUE THREAD

**Issue by yuyat** [alastria/alastria-node#804]
Hola:

He probado levantar un nodo regular empleando Docker y también manualmente, pero en ambos casos termina con el mismo error. 

`panic: failed to create bloom: m (number of bits in the Bloom filter) must be >= 2`

![image](https://user-images.githubusercontent.com/5240483/100004201-77685480-2dc7-11eb-8b03-6b6799be18ea.png)

¿Alguna idea de lo que esta fallando? Gracias de antemano.

**Comment by alejandroalffer** [comment]
Hola!

Casi seguro que sea por la cache... prueba a arrancar _geth_ con este argumento adicional:

```sh
--cache 10
```

Posiblemente ahora esté el valor a "0"

Si el problema persiste, envíanos un "ps aux" del geth y seguro que encontramos una solucion

Saludos!

**Comment by yuyat** [comment]
> Hola!
> 
> Casi seguro que sea por la cache... prueba a arrancar _geth_ con este argumento adicional:
> 
> ```shell
> --cache 10
> ```
> 
> Posiblemente ahora esté el valor a "0"
> 
> Si el problema persiste, envíanos un "ps aux" del geth y seguro que encontramos una solucion
> 
> Saludos!

Hola Alejando, tienes razón es el valor 0 del parámetro cache. Se encuentra en el script de start.sh. Hice el cambio conectandome al contenedor mientras se intalaban las dependencias y ahora el nodo funciona correctamente. 

https://github.com/alastria/alastria-node/blob/bb4bd3f3ff6c15d0895cc32fe929d42a7b0a4972/scripts/start.sh#L103


![image](https://user-images.githubusercontent.com/5240483/100087754-7549d880-2e4f-11eb-9acf-03308327b868.png)

**Comment by alejandroalffer** [comment]
Cerramos la issue! Un saludo!
