### ISSUE TITLE
Error en el contenedor al ejecutar ./ini.sh

### ISSUE THREAD

**Issue by cibervoluntarios** [alastria/alastria-node#810]
Estamos intentando poner en marcha un nodo regular en la red Telsius de Alastria siguiendo las instrucciones tanto del repositorio como del manual https://medium.com/babel-go2chain/c%C3%B3mo-poner-en-marcha-un-nodo-regular-en-la-red-telsius-de-alastria-876d9dcf7ccb pero al lanzar ./ini.sh llega a este punto el contenedor y rompe la instalación.

Se trata de un SV o droplet de DigitalOcean (Ubuntu 16.04 TLS x64 2 procesadores y 4 Gb de RAM)
Pero independientemente del tutorial o pasos siempre rompe en el mismo punto.

`Monitor disabled.
Logrotate disabled.
INFO [12-10|15:20:15.232|internal/debug/flags.go:161] Starting pprof server                    addr=http://0.0.0.0:9545/debug/pprof
DEBUG[12-10|15:20:15.233|geth/main.go:318]            Sanitizing Go's GC trigger               percent=100
INFO [12-10|15:20:15.233|cmd/utils/flags.go:1918]     Enabling metrics collection 
INFO [12-10|15:20:15.234|cmd/utils/flags.go:1930]     Enabling metrics export to InfluxDB 
INFO [12-10|15:20:15.236|cmd/utils/flags.go:1256]     Maximum peer count                       ETH=50 LES=0 total=50
INFO [12-10|15:20:15.236|cmd/utils/flags.go:1336]     Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[12-10|15:20:15.236|accounts/keystore/file_cache.go:87] FS scan times                            list=71.021µs set=6.143µs diff=2.856µs
TRACE[12-10|15:20:15.237|accounts/keystore/account_cache.go:299] Handled keystore changes                 time=243.063µs
TRACE[12-10|15:20:15.238|accounts/keystore/watch.go:73]          Started watching keystore folder         path=/root/alastria/data/keystore
ERROR[12-10|15:20:15.241|accounts/usbwallet/hub.go:170]          Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[12-10|15:20:15.241|accounts/usbwallet/hub.go:170]          Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[12-10|15:20:15.242|accounts/usbwallet/hub.go:170]          Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[12-10|15:20:15.242|accounts/usbwallet/hub.go:170]          Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[12-10|15:20:15.242|accounts/usbwallet/hub.go:170]          Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[12-10|15:20:15.243|accounts/usbwallet/hub.go:170]          Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
WARN [12-10|15:20:15.243|node/config.go:501]                     permission-config.json file is missing. Smart-contract-based permission service will be disabled error="stat /root/alastria/data/permission-config.json: no such file or directory"
WARN [12-10|15:20:15.244|node/config.go:592]                     Found deprecated node list file /root/alastria/data/static-nodes.json, please use the TOML config file instead. 
INFO [12-10|15:20:15.246|node/node.go:199]                       Starting peer-to-peer node               instance=Geth/REG_FundacionCibervoluntarios_T_2_4_00/v1.9.7-stable-af752518(quorum-v20.10.0)/linux-amd64/go1.15.2
INFO [12-10|15:20:15.246|eth/backend.go:137]                     Allocated trie memory caches             clean=0.00B dirty=0.00B
INFO [12-10|15:20:15.246|ethdb/leveldb/leveldb.go:95]            Allocated cache and file handles         database=/root/alastria/data/geth/chaindata cache=16.00MiB handles=524288
DEBUG[12-10|15:20:15.267|core/rawdb/freezer_table.go:305]        Chain freezer table opened               database=/root/alastria/data/geth/chaindata/ancient table=diffs items=0 size=0.00B
DEBUG[12-10|15:20:15.269|core/rawdb/freezer_table.go:305]        Chain freezer table opened               database=/root/alastria/data/geth/chaindata/ancient table=headers items=0 size=0.00B
DEBUG[12-10|15:20:15.272|core/rawdb/freezer_table.go:305]        Chain freezer table opened               database=/root/alastria/data/geth/chaindata/ancient table=hashes  items=0 size=0.00B
DEBUG[12-10|15:20:15.274|core/rawdb/freezer_table.go:305]        Chain freezer table opened               database=/root/alastria/data/geth/chaindata/ancient table=bodies  items=0 size=0.00B
DEBUG[12-10|15:20:15.276|core/rawdb/freezer_table.go:305]        Chain freezer table opened               database=/root/alastria/data/geth/chaindata/ancient table=receipts items=0 size=0.00B
INFO [12-10|15:20:15.276|core/rawdb/freezer.go:123]              Opened ancient database                  database=/root/alastria/data/geth/chaindata/ancient
DEBUG[12-10|15:20:15.277|core/state/statedb.go:118]              Privacy metadata root                    hash=000000…000000
INFO [12-10|15:20:15.278|eth/backend.go:148]                     Initialised chain configuration          config="{ChainID: 83584648538 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 IsQuorum: true Constantinople: <nil> TransactionSizeLimit: 64 MaxCodeSize: 0 Petersburg: <nil> Istanbul: <nil> PrivacyEnhancements: <nil> Engine: istanbul}"
DEBUG[12-10|15:20:15.278|core/rawdb/freezer.go:273]              Current full block not old enough        number=0 hash=77a8c9…dd474c delay=3162240
INFO [12-10|15:20:15.280|eth/backend.go:193]                     Initialising Ethereum protocol           name=istanbul versions="[99 64]" network=83584648538 dbversion=<nil>
WARN [12-10|15:20:15.280|eth/backend.go:199]                     Upgrade blockchain database version      from=<nil> to=7
DEBUG[12-10|15:20:15.281|core/state/statedb.go:118]              Privacy metadata root                    hash=000000…000000
DEBUG[12-10|15:20:15.281|core/state/statedb.go:118]              Privacy metadata root                    hash=000000…000000
INFO [12-10|15:20:15.282|core/blockchain.go:404]                 Loaded most recent local header          number=0 hash=77a8c9…dd474c td=1 age=51y8mo6d
INFO [12-10|15:20:15.283|core/blockchain.go:405]                 Loaded most recent local full block      number=0 hash=77a8c9…dd474c td=1 age=51y8mo6d
INFO [12-10|15:20:15.283|core/blockchain.go:406]                 Loaded most recent local fast block      number=0 hash=77a8c9…dd474c td=1 age=51y8mo6d
DEBUG[12-10|15:20:15.285|core/state/statedb.go:118]              Privacy metadata root                    hash=000000…000000
DEBUG[12-10|15:20:15.285|core/state/statedb.go:118]              Privacy metadata root                    hash=000000…000000
DEBUG[12-10|15:20:15.286|core/tx_pool.go:1184]                   Reinjecting stale transactions           count=0
INFO [12-10|15:20:15.286|core/tx_journal.go:166]                 Regenerated local transaction journal    transactions=0 accounts=0
**panic: failed to create bloom: m (number of bits in the Bloom filter) must be >= 2**

goroutine 1 [running]:
github.com/ethereum/go-ethereum/trie.NewSyncBloom(0x0, 0x7f31e640b5f0, 0xc0001f4160, 0x7f31e640b5f0)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/sync_bloom.go:73 +0x28b
github.com/ethereum/go-ethereum/eth.NewProtocolManager(0xc000024380, 0x0, 0x1, 0x137608855a, 0xc00034b0b0, 0x17e04a0, 0xc000030000, 0x7f31e640a3b0, 0xc0002786c0, 0xc00032c000, ...)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:169 +0x7a5
github.com/ethereum/go-ethereum/eth.New(0xc0001f4e40, 0xc0004d4000, 0x424098, 0x30, 0x14d93e0)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:240 +0xd3f
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc0001f4e40, 0xc0003d4390, 0xc00059f970, 0xc0001f4e00, 0x2)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1751 +0x4f
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc000403900, 0x0, 0x0)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:216 +0x463
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc000403900)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc000348420, 0xc000403900)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:362 +0x10f
main.geth(0xc000348420, 0x0, 0x0)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:339 +0x127
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x131c8a0, 0x1643d40, 0xc000348420, 0xc0003ac660, 0x0)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0x82
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0003d8680, 0xc00003ce00, 0x35, 0x38, 0x0, 0x0)
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5f5
main.main()
	/tmp/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:278 +0x55`

**Comment by cmoralesdiego** [comment]
Buenas @cibervoluntarios , tendríais mañana un hueco a primera hora para hacer un teams?

**Comment by cibervoluntarios** [comment]
Sï, 
Confírmame la hora y el enlace de teams al email alfonso.peon@cibervoluntarios.org o cualquier otra información privada.
Gracias

**Comment by cibervoluntarios** [comment]
Hola, después del Pull request sigo teniendo problemas, porque el  nodo está en rojo y sin sincronizar. ¿Alguien me puede decir qué puede estar pasando? Gracias

**Comment by cmoralesdiego** [comment]
@cibervoluntarios , hemos visto que tenéis el nodo parado, es así?, voy a proceder a cerrar este issue porque lleva mucho tiempo parado, para cualquier otra cosa, abrid otro nuevo.
