### ISSUE TITLE
actualización nodo

### ISSUE THREAD

**Issue by dvgoyeneche** [alastria/alastria-node#833]
Tras actualizar el nodo siguiendo los pasos de 
https://github.com/alastria/alastria-node/blob/testnet2/UPGRADE_TO_LAST_VERSION.md

El nodo permanece en este estado
Geth
Version: 1.8.12-stable
Quorum Version: 2.2.0-0.Alastria_EthNetstats_IBFT
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.5
Operating System: linux
GOPATH=/root/alastria/workspace
GOROOT=/usr/local/go

¿No debería de haber subido a la versión 1.9.7?

**Comment by dvgoyeneche** [comment]
De hecho tengo la sospecha de que al hacer el update ha bajado de versión... de 1.8.18 a 1.8.12

**Comment by cmoralesdiego** [comment]
Buenas @dvgoyeneche , actualmente estamos en fase de pruebas dado que las últimas versiones, la 20.10 y 21.01 nos está dando problemas en un bloque de la cadena. Si estás en la versión 1.8.12, deberías poder subir a la 1.8.18 que es donde el apunta el git checkout que está en el fichero de bootstrap.sh que llama el el update. Dicho hash es el : 775aa2f5a6a52d9d84c85d5ed73521a1ea5b15b3 . Muchas gracias

**Comment by dvgoyeneche** [comment]
Pero hay nodos funcionando en version superior, por ejemplo VAL_IN2_Telsius_2_8_00 en http://netstats.telsius.alastria.io/

**Comment by cmoralesdiego** [comment]
@dvgoyeneche , También he visto que tu repo, lo tienes bastante desactualizado, por eso has vuelto a una versión 1.8.12 de Quorum: https://github.com/dvgoyeneche/alastria-node/ . En cuanto a lo que indicas de IN2, es correcto lo que indicas, pero como te digo, la tónica general es esta, hay un fallo en un bloque y se está buscando la solución. Mientras tanto, se continua con la versión 1.8.18. Gracias

**Comment by dvgoyeneche** [comment]
No entiendo la relación entre mi repositorio de github y la versión en la que termina el nodo cuando se lanza el update.sh
He actualizado mi repositorio y he vuelto a lanzar la actualización y se me vuelve a ir a 1.8.12

**Comment by cmoralesdiego** [comment]
Buenas @dvgoyeneche , comprueba que en los scripts de tu nodo en el bootstrap está esta linea: git checkout 775aa2f5a6a52d9d84c85d5ed73521a1ea5b15b3, esto quiere decir que se instale la versión 1.8.18, verificalo porfa. La secuencia de comandos a ejecutar para actualizar son estos comandos como habrás visto:

1. ./update.sh
2. ./stop.sh
3. ./bootstrap.sh reinstall
4. ./start.sh

En el tercer comando es donde se ejecuta ese git checkout que te comento. Por otro lado, en el fichero .md @alejandroalffer escribió, como te dije en el día de ayer que es experimental dado que como te comenté ayer estamos actualmente en fase de pruebas con la nueva versión ya que estamos presentando algunos problemas. Gracias

**Comment by dvgoyeneche** [comment]
perfecto, solucionado
Saludos

**Comment by cmoralesdiego** [comment]
Genial. Cierro el issue entonces. Gracias
