### ISSUE TITLE
New regular node for UEx - Alastria-T Network

### ISSUE THREAD

**Issue by javierrome236** [alastria/alastria-node#858]
Enode:
enode://156d27b244d3902c155adb26fe5894b1037e26c02939e83177f1070b25efb1eef08e1344ab316d01ae6a7d7604d088683041502dd2649f09b7d9588a7bcbb3ca@127.0.0.1:21000

IP:
34.252.17.130

DATA:
| REG_UEx_T_2_4_00 | AWS (2C/4GB/180GB) | | enode://156d27b244d3902c155adb26fe5894b1037e26c02939e83177f1070b25efb1eef08e1344ab316d01ae6a7d7604d088683041502dd2649f09b7d9588a7bcbb3ca@34.252.17.130:21000?discport=0 |

**Comment by alejandroalffer** [comment]
Added node, and restarted DigitelTS bootnode
