### ISSUE TITLE
No actualiza ENODE en ficheros JSON al inicializar un nodo general

### ISSUE THREAD

**Issue by blockchain-ctic** [alastria/alastria-node#86]
Al lanzar el script "init.sh auto general XXXXX" los ficheros ~/alastria/data/permissioned-nodes.json y ~/alastria/data/static-nodes.json no contienen el ENODE recien creado. El fichero constellation.conf si se actualiza adecuadamente.

**Comment by arochaga** [comment]
Tras revisarlo con @marcossanlab este es el comportamiento correcto. En los nodos generales estos ficheros no deberían actualizarse.

Cierro el issue, si veis que hay algo adicional que comentar lo reabrimos.

**Comment by blockchain-ctic** [comment]
Pues hay algo que no entiendo muy bien porque se hace así. En los nodos generales al inicializar se copia el ENODE del nuevo nodo a permissioned-nodes_validator.json, que luego supuestamente sólo se usa para generar el permissioned-nodes.json de los validadores. Sin embargo, el permissioned-nodes_general.json solo se actualiza cuando se inicializa un validador (ver codigo más abajo) y luego es este archivo el que utiliza el nodo general para generar su permissioned-nodes.json. El efecto final es que ninguno de los nodos generales puede conectar con ningún nodo que no esté en ese permissioned-nodes.json y que además sea validador (para que puede reconocer también a su vez a este nuevo nodo). En pocas palabras, me parece que ningún nodo general va a poder conectarse a otro nodo general puesto que nunca aparecerá en su permissioned-nodes.json. Es esta la funcionalidad buscada?

`update_nodes_list() {
    echo "Selected $NODE_TYPE node..."
    echo "Updating permissioned nodes..."

       ENODE=",
    \"$1\"
]"
    PERMISSIONED_NODES_VALIDATOR=${PERMISSIONED_NODES_VALIDATOR::-2}
    PERMISSIONED_NODES_VALIDATOR="$PERMISSIONED_NODES_VALIDATOR$ENODE"
    echo "$PERMISSIONED_NODES_VALIDATOR" > ~/alastria-node/data/permissioned-nodes_validator.json

    if ( [ "validator" == "$NODE_TYPE" ]); then 
        PERMISSIONED_NODES_GENERAL=${PERMISSIONED_NODES_GENERAL::-2}
        PERMISSIONED_NODES_GENERAL="$PERMISSIONED_NODES_GENERAL$ENODE"
        echo "$PERMISSIONED_NODES_GENERAL" > ~/alastria-node/data/permissioned-nodes_general.json
    fi

    echo "Updating static-nodes..."
    cp ~/alastria-node/data/permissioned-nodes_general.json ~/alastria-node/data/static-nodes.json

}
`

**Comment by arochaga** [comment]
Eso es. Los nodos generales solo necesitan ver a los validadores. Toda comunicación entre nodos generales se realiza a través de la propia blockchain, o eventos a través de ella. De ahí que el permisiones_nodes_general solo incluya a los validadores.

Son los validadores los encargados de extender los nuevos bloques a través de toda la red, y para contratos privados entre dos nodos regulares, esto se hace con ayuda de los nodos constellations, no se necesita visión directa entre los nodos Quorum.

Espero que haya quedado algo más claro. De todas formas, si quieres que miremos juntos el funcionamiento o concretemos algún tema te facilito mi contacto y lo hablamos.
