### ISSUE TITLE
Error al ejecutar ./init.sh

### ISSUE THREAD

**Issue by marcosfdzmdz** [alastria/alastria-node#862]
Buenos días,
Al ejecutar el script ./init.sh sale el siguiente error:

![error](https://user-images.githubusercontent.com/86839724/124906435-57e50b80-dfe7-11eb-99c5-5c1a9cb366ec.jpeg)

Sin embargo el nodo aparece en la página de [monitoreo](http://netstats.telsius.alastria.io/). ¿Alguna idea de qué podría ser ese error?

Gracias

**Comment by marcosfdzmdz** [comment]
Somos conscientes de que este mensaje es solo un warning, por lo que nos gustaría saber si podemos seguir adelante con la Pull Request y una vez aceptada lo arreglamos. O si, por el contrario debemos solucionarlo antes de llevar a cabo dicha Pull Request.

**Comment by alejandroalffer** [comment]
Hola!

Efectivamente, la captura muestra que el nodo ha sido iniciado correctamente. Los Warning que se están motivados por que tu nodo aún no ha sido permisionado.

Por favor, echa un vistazo a esta documentación, https://github.com/alastria/alastria-node-quorum/blob/main/README.md, en particular donde se hace referencia al uso de `geth` para obtener la información de tu `enode` y que podamos hacer el permisonado: una vez aprovada la petición, los mensajes de Waring cambiarán a mensajes de sincronización de nodo.

Un saludo!
