### ISSUE TITLE
Update nodo Innogando

### ISSUE THREAD

**Issue by marcosfdzmdz** [alastria/alastria-node#866]
En el fichero DIRECORY_REGULAR.md:
| REG_Innogando_T_2_4_00 | Google Cloud Plataform (2C/4GB/128GB) |  | enode://55b2e4c037c9efcf6167865793208d3c25f6f80eefc684dbb952ae1f91b37fbb8310be58648fda9ba4f7cabe88f7d78679f2b8c6a5f2c6b8ef2e4b4085fc5c9d@34.79.5.142:21000?discport=0 |

En el fichero data/constellation-nodes.json **eliminar linea** (no hemos instalado constellation):
"https://34.77.112.117:9000/"

En el fichero data/regular-nodes.json:
"enode://55b2e4c037c9efcf6167865793208d3c25f6f80eefc684dbb952ae1f91b37fbb8310be58648fda9ba4f7cabe88f7d78679f2b8c6a5f2c6b8ef2e4b4085fc5c9d@34.79.5.142:21000?discport=0"

**Comment by alejandroalffer** [comment]
Actualizada la información de vuestro nodo, y reiniciado nodo boot de DigitelTS

Aún no veo el enode sincronizando: aseguraros de tener corriendo geth, o abridme el issue si tuvieráis algún problema
