### ISSUE TITLE
Nodo no sincroniza

### ISSUE THREAD

**Issue by BrayanSoria** [alastria/alastria-node#878]
Buenos días,

Estamos teniendo varios problemas de sincronización con uno de nuestros nodos (REG_WISE_ALASTRIA_DES_T_2_4_00), ya que este deja de sincronizar repentinamente.

Hemos encontrado una incidencia similar.  https://github.com/alastria/alastria-node/issues/751

Os pasamos los datos solicitados en esta incidencia:

> **admin.nodeInfo**
{
  enode: "enode://871b679aabceb6b2ed95ac87e5eeac5886a872725294eafe86a982f88d627a1153abc6b73adb11b1d08ced937c441f8690fdf7ca7af194e27ffd0f85b60356c6@127.0.0.1:21000?discport=0",
  enr: "0xf894b8408284da326e710fb0bf1cef8c5cb4e79311840d3c64c697649d858194f92e62f944522126d95e6b509ffce12580ae23732859aef5f13c8b9f79109437cff49e690c83636170cbca88697374616e62756c40826964827634826970847f00000189736563703235366b31a102871b679aabceb6b2ed95ac87e5eeac5886a872725294eafe86a982f88d627a1183746370825208",
  id: "cb77f28e48a24df0eacaa8a13e2525e64ee1cfdcad102b2e2c8d3169cd83f7c7",
  ip: "127.0.0.1",
  listenAddr: "[::]:21000",
  name: "Geth/REG_WISE_ALASTRIA_DES_T_2_4_00/v1.8.18-stable(quorum-v2.2.3-0.Alastria_EthNetstats_IBFT)/linux-amd64/go1.9.5",
  ports: {
    discovery: 0,
    listener: 21000
  },
  protocols: {
    istanbul: {
      config: {
        byzantiumBlock: 0,
        chainId: 83584648538,
        eip150Block: 0,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0,
        isQuorum: true,
        istanbul: {...},
        txnSizeLimit: 64
      },
      difficulty: 76293510,
      genesis: "0x77a8c93fdee76dcbe099afcda0ee6b2856a0fbebc30fd6bee45ca1a555dd474c",
      head: "0x25bc7d43986f0677cbdc260183ed63e7c8673d30ee7199f9699b4fe32b8c19a0",
      network: 83584648538
    }
  }
}

> **admin.peers**
[{
    caps: ["istanbul/64", "istanbul/99"],
    enode: "enode://d7d50abadb467de05cf474c6c9d1b2b3a399de9ccb1a58ea26141509f6a05c7b68690c8cba812d4db0258add29c349af88f9e61e5ada1c674b16c302083627b8@54.228.169.138:21000?discport=0",
    id: "a2054ebfafb0f0f5d5aba7068e1f14829e69dace06ad91a4ce23012984de1f06",
    name: "Geth/BOT_DigitelTS_T_2_8_00/v1.9.7-stable-a21e1d44(quorum-v21.1.0)/linux-amd64/go1.15.5",
    network: {
      inbound: false,
      localAddress: "172.17.0.2:59522",
      remoteAddress: "54.228.169.138:21000",
      static: true,
      trusted: false
    },
    protocols: {
      istanbul: {
        difficulty: 2817,
        head: "0x9f0316cefb28672d12bbc799e17c6e0fb6637f2bf7b53158d4b85603aef806c0",
        version: 64
      }
    }
}]

**df -h**

Filesystem      Size  Used Avail Use% Mounted on
overlay         7.9G  6.7G  791M  90% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/vdb1       196G   77G  110G  42% /root/alastria
/dev/vda1       7.9G  6.7G  791M  90% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           7.9G     0  7.9G   0% /proc/acpi
tmpfs           7.9G     0  7.9G   0% /sys/firmware

**df -i**

Filesystem       Inodes  IUsed    IFree IUse% Mounted on
overlay          524288 179112   345176   35% /
tmpfs           2053459     16  2053443    1% /dev
tmpfs           2053459     16  2053443    1% /sys/fs/cgroup
/dev/vdb1      13107200  69136 13038064    1% /root/alastria
/dev/vda1        524288 179112   345176   35% /etc/hosts
shm             2053459      1  2053458    1% /dev/shm
tmpfs           2053459      1  2053458    1% /proc/acpi
tmpfs           2053459      1  2053458    1% /sys/firmware

Por lo general, al reiniciar el nodo este vuelve a sincronizar.

¿Podéis comentarnos alguna solución?

Un saludo.

**Comment by alejandroalffer** [comment]
I can the see your node connected to this bootnode:

```
root@e8cdc103b174:~# geth attach /root/alastria/data/geth.ipc --exec "admin.peers"|grep 871b679aabceb6b2ed95ac87e5eeac5886a872725294eafe86a982f88d627a1153abc6b73adb11b1d08ced937c
    enode: "enode://871b679aabceb6b2ed95ac87e5eeac5886a872725294eafe86a982f88d627a1153abc6b73adb11b1d08ced937c441f8690fdf7ca7af194e27ffd0f85b60356c6@51.38.122.170:59522",
```

Please, try restarting `geth` or the docker that runs the node

**Comment by cmoralesdiego** [comment]
Puede ser por los recursos de la máquina donde esté alojado el nodo

**Comment by cmoralesdiego** [comment]
Podrías hacernos llegar los logs del nodo de alguna manera?. Gracias

**Comment by BrayanSoria** [comment]
Buenos días,

Lo único que vemos en los logs es :

Imported new chain segment               blocks=1    txs=0   mgas=0.000  elapsed=1.655ms   mgasps=0.000    number=77316617 hash=47cbc3…dfc1af cache=26.50mB
WARN [10-02|16:17:02.246] Failed to decode stats server message    err="json: cannot unmarshal string into Go value of type map[string][]interface {}"
WARN [10-02|16:17:02.825] Full stats report failed                 err="write tcp 172.17.0.2:50816->185.180.8.152:80: use of closed network connection"
INFO [10-02|16:17:03.081] Imported new chain segment               blocks=1    txs=0   mgas=0.000  elapsed=1.683ms   mgasps=0.000    number=77316618 hash=b9eb82…c32007 cache=26.50mB
INFO [10-02|16:17:04.619] Imported new chain segment               blocks=1    txs=0   mgas=0.000  elapsed=1.930ms   mgasps=0.000    number=77316619 hash=2b665d…5b258f cache=26.50mB


En nuestro caso hemos aumentado los recursos de nuestra máquina, debemos modificar algún fichero para reflejar este cambio?

El nodo deja de sincronizar sin dar ningún error aparente, y al reiniciar vuelve a sincronizar.

**Comment by BrayanSoria** [comment]
Nuestro nodo muestra que se encuentra sincronizando, pero el currentBlock no varía, lleva así desde ayer.

  syncing: {
    currentBlock: 77316619,
    highestBlock: 77541817,
    knownStates: 0,
    pulledStates: 0,
    startingBlock: 77316619
  },

**Comment by BrayanSoria** [comment]
Hemos optado por reinstalar el nodo, gracias.
