### ISSUE TITLE
Inicializar nodo de Alastria

### ISSUE THREAD

**Issue by alvarogarmig** [alastria/alastria-node#9]
Hola, según tengo entendido para poder empezar a realizar transacciones en la red Alastria hay que notificar al administrador de la red la cuenta de mi nodo para que realice una transferencia y poder habilitar ese nodo, ¿como me pongo en contacto con ese administrador?

Muchas Gracias!

**Comment by marcossanlab** [comment]
Buenos días,

Estamos en proceso de reiniciado de la red Alastria.

En este momento, los nodos core está parados y es necesario que todos los demás lo estén.

Después, envía por correo a marcos@sanlab.io y a juanluis.garcia@isban.com para que dotemos de fondos la cuenta del nodo.

Un saludo

**Comment by alvarogarmig** [comment]
Hola Marcos, ok.

Te he mandado por correo la cuenta y la dirección del nodo.

Muchas Gracias por tu atención.
